### ISSUE TITLE
Enhance country detection

### ISSUE THREAD

**Issue by Toilal** [guessit-io/guessit#166]
See https://github.com/wackou/guessit/pull/165

I think it's a good idea @Nikola-K

I you wan't to work of this, perhaps you could reuse an internal feature called Validator that can be used to validate regexp results based on position. See https://github.com/wackou/guessit/blob/master/guessit/containers.py#L149 all classes starting with validator.

**Comment by ratoaq2** [comment]
@Toilal is there a clear scope of this issue or this is only an old one?

**Comment by Toilal** [comment]
Yes, it's too old :)
