### ISSUE TITLE
Team name in filename

### ISSUE THREAD

**Issue by kamaradclimber** [guessit-io/guessit#196]
Does guessit try to eliminate extra words such as team names?

Detecting title in `ulshd-the.right.stuff.1983.multi.1080p.bluray.x264.mkv` gives: `[0.60] "title": "ulshd-the right stuff"`.

I realize this might be hard (and I have no idea how match tree works).

Random suggestions:
- try remove non-dictionary words and check if confidence increase
- hardcode some team names (non sustainable since they change all the time)
- find common file naming convention accross teams and add them in guessit

**Comment by Toilal** [comment]
It would work if `ulshd` was in between brakets, like `[ulshd]-the.right.stuff.1983.multi.1080p.bluray.x264.mkv`.

Actually, I don't think we can really do this better with the 3 options you have mentionned. But maybe, we could detect more separators patterns, to find out that ulshd is in another textual group than the rest, because it's separated by a `-`, and the rest is separated by a `.`.

**Comment by ratoaq2** [comment]
The release group is not guessed correctly:

```
guessit "Z.Nation.S02E13.720p.HDTV.x264-KILLERS[ettv].mkv"
For: Z.Nation.S02E13.720p.HDTV.x264-KILLERS[ettv].mkv
GuessIt found: {
    "title": "Z Nation",
    "season": 2,
    "episode": 13,
    "screen_size": "720p",
    "format": "HDTV",
    "video_codec": "h264",
    "release_group": "KILLERS[ettv]",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

The [ettv] shouldn't be part of the release_group in this case.

**Comment by Toilal** [comment]
Discussed many times in various issues, it belongs the release group. Post
process in your own application if you want to remove brakets part.

**Comment by ratoaq2** [comment]
Thank you. I wasn't aware of it.

**Comment by ratoaq2** [comment]
Just to add an additional information to thus issue:

Most of these cases, only the file name starts with the release group... And the parent folder has the title as expected and the release group at the end. 

With guessit 2.0.5, if you include the parent folder,  the guess might be corrected:

As you can see:
```
guessit "How.To.Be.Single.2016.1080p.BluRay.x264-BLOW/blow-how.to.be.single.2016.1080p.bluray.x264.mkv"
For: How.To.Be.Single.2016.1080p.BluRay.x264-BLOW/blow-how.to.be.single.2016.1080p.bluray.x264.mkv
GuessIt found: {
    "title": "How To Be Single", 
    "year": 2016, 
    "screen_size": "1080p", 
    "format": "BluRay", 
    "video_codec": "h264", 
    "release_group": "BLOW", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "movie"
}
```
