### ISSUE TITLE
Move to organization guessit-io

### ISSUE THREAD

**Issue by Toilal** [guessit-io/guessit#239]
Hi @wackou and @Diaoul.

Could we move the repository to an organization ? Sadly, guessit is already taken as an organization name. But I've create guessit-io and sent invitations ...

I want to use an Automated build in docker Hub, but it requires the repository to be either in my own username space, or in an organization I belong to ... Also, I've created [guessit-rest](https://github.com/Toilal/guessit-rest) and i'm planning to create a guessit-webapp too. I'll move those repository to the new organization too.

Also I would like to use the guessit.io domain name on my own server to host those new things, would it be possible ?

**Comment by Diaoul** [comment]
I accepted the invite. The webservice is great, where do you plan hosting it?

**Comment by Toilal** [comment]
I rent this server : https://www.online.net/fr/serveur-dedie/dedibox-xc.

**Comment by Toilal** [comment]
@wackou when you have joined the organization, you can transfert ownership of this repository to guessit-io. It will move it to the new url https://github.com/guessit-io/guessit, and perform all required redirections at the old one. I've just done it for the guessit-rest repository initialy located in my own account.

**Comment by wackou** [comment]
@Toilal I just accepted the invite, but can't transfer ownership yet because I require you to give me admin right in the guessit-io org first. As for the dns redirection, let me know when you have your server set up and your ip address and I'll update it.

**Comment by Toilal** [comment]
You are now admin :). IP of my server is 62.210.182.194. Could you only configure `v2.api.guessit.io` subdomain to this IP ?

**Comment by wackou** [comment]
dns entry is updated, should take effect in a couple of hours. As for the repo transfer, it still won't let me, even though I can see myself as admin. Probably I think I also need to be owner of the organization

**Comment by Toilal** [comment]
@wackou This is strange, it should work ... Maybe we could chat ? I've opened at chatroom at gitter.im : https://gitter.im/guessit-io

**Comment by Toilal** [comment]
@wackou You are now owner, I've found the option to give you ownership in the member list of guessit-io organization. Could you try again ?

**Comment by wackou** [comment]
Ok, it worked now :)
