### ISSUE TITLE
v2 UnicodeEncodeError

### ISSUE THREAD

**Issue by mark-hahn** [guessit-io/guessit#241]
I getting this error even though I don't see any unicode in the file name using the `ls` command.  Even if there is a bad character guessit shouldn't crash.  I would suggest just removing the out-of-range character.

```
For: Madam Secretary - 1x14 - Whisper of the Ax.mkv
GuessIt found: ,Traceback (most recent call last):
  File "/usr/local/bin/guessit", line 9, in <module>
    load_entry_point(\'guessit==2.0rc4\', \'console_scripts\', \'guessit\')()
  File "/usr/local/lib/python2.7/dist-packages/guessit/__main__.py", line 151, in main
    guess_filename(filename, options)
  File "/usr/local/lib/python2.7/dist-packages/guessit/__main__.py", line 57, in guess_filename
    print(\'GuessIt found:\', json.dumps(guess, cls=GuessitEncoder, indent=4, ensure_ascii=False))
UnicodeEncodeError: \'ascii\' codec can\'t encode character u\'\\xc5\' in position 134: ordinal not in range(128)
```

**Comment by Toilal** [comment]
In fact, Ax is detected as a contry, and this country as the failing character.

```
For: Madam Secretary - 1x14 - Whisper of the Ax.mkv
GuessIt found: {
    "title": "Madam Secretary (AX)",
    "season": 1,
    "episode": 14,
    "episode_title": "Whisper of the",
    "country": "ÅLAND ISLANDS",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

But it works on my computer, you surely have something weird with encoding in your OS. Do you run windows ?

**Comment by mark-hahn** [comment]
I just used guessit on the command line and it gave the same results as you got.  The problem occurred when calling guessit from node.  I assume it is a problem in my code.  I will chase the problem asap.

I apologize for the false alarm.  I will test all examples on the command line from now on.
