### ISSUE TITLE
Release type in title

### ISSUE THREAD

**Issue by oxan** [guessit-io/guessit#243]
Currently, guessit doesn't try to strip release "types" (such as extended, retail, uncut, etc) from the title. it'd be nice if these could be removed.

So far I've encountered the following tags:
* EXTENDED
* EXTENDED CUT
* AVCHD
* FIXED
* RETAIL
* REAL
* UNCUT

**Comment by Toilal** [comment]
Thanks for reporting those keywords. Maybe it could be added to [other](https://github.com/guessit-io/guessit/blob/master/guessit/rules/properties/other.py#L25-L54) property ?

**Comment by Toilal** [comment]
Could you provide the whole filenames where it fails ? `Real` and be guessed as `other` = `Proper` if next to another tag.

**Comment by Toilal** [comment]
From what I can find on google, ACVHD seems to be a variant of h264, so it'll be guessed as `video_codec` = `h264` value. (In fact, most often it's tagged with `x264-AVCHD`).

Other values will be added in `others` property possible values. Feel free to reopen if needed.
