### ISSUE TITLE
Wrong guess for Scrubs

### ISSUE THREAD

**Issue by oxan** [guessit-io/guessit#244]
Any guess for the show Scrubs (such as `Scrubs/SEASON-06/Scrubs.S06E09.My.Perspective.DVDRip.XviD-WAT/scrubs.s06e09.dvdrip.xvid-wat.avi`) gives the title split in two parts (Scr and ubs). 

I think it recognises the SCR as a tag for DVD screeners, but that isn't useful in this case.

**Comment by Toilal** [comment]
Fixed in master
