### ISSUE TITLE
Incorrect container detection with adult content

### ISSUE THREAD

**Issue by labrys** [guessit-io/guessit#254]
Word `Ass` in adult content detected as `ASS` container type.

```
TeenPornoPass - Anna - Beautiful Ass Deep Penetrated 720p mp4
    other properties:
        alternativeTitle: Anna
    video properties:
        screen_size: 720p
    main properties:
        container: Ass
        title: TeenPornoPass

SexInJeans.Gina.Gerson.Super.Nasty.Asshole.Pounding.With.Gina.In.Jeans.A.Devil.In.Denim.The.Finest.Ass.Fuck.Frolicking.mp4
    main properties:
        mimetype: video/mp4
        container: Ass
        title: SexInJeans Gina Gerson Super Nasty Asshole Pounding With Gina In Jeans A Devil In Denim The Finest
```

**Comment by Toilal** [comment]
In this case, it could be considered as a container :D (kidding).

**Comment by Toilal** [comment]
Problem is that ass is a container filetype ... That beeing said, it's not consistent with the mimetype, so maybe we could use that to invalidate the container.

**Comment by Toilal** [comment]
I'll fix this one after 2.0 release. Not that critical :)

**Comment by Con7e** [comment]
@labrys This might be off-topic, but what's the use case for using guessit with porn? Considering porn doesn't have seasons/episodes or a standard way of defining a video (every filename is very unpredictable as in what it contains) how does one standardise the un-standardizable? 

Just curious :)

**Comment by labrys** [comment]
@Con7e it's actually more for identification for purposes of exclusion when parsing search results/rss feeds etc.  As a developer for [Medusa](http://github.com/pymedusa/sickrage), a SickBeard/SickRage fork, we're looking at extending the search capabilities and this would add an additional level of validation among other things.

**Comment by ratoaq2** [comment]
Fixed by https://github.com/guessit-io/guessit/commit/c9ef77fce8c38badeaa737d4cc7822050b4d6ff9
