### ISSUE TITLE
Avoid dependency on regex module

### ISSUE THREAD

**Issue by Toilal** [guessit-io/guessit#257]
Regex module is a native module requiring a C toolchain, and it can cause problems in some embeded systems.

**Comment by labrys** [comment]
:+1: This would be the biggest barrier to implementation for SickRage since we support a wide variety of platforms.

**Comment by Toilal** [comment]
I now works actively on this now. It was a mistake to use regex native module from the beginning. It has make things really simpler with support of repeated captures, but sadly it's not an option to use it :(

Currently, i'm introducing a new rebulk API to support something that would nicely replace those repeated captured groups, but using the default python re module. When it's done, regex native module will be at least optional, or maybe simply removed.

**Comment by labrys** [comment]
\o/
