### ISSUE TITLE
Country matches 92% correct

### ISSUE THREAD

**Issue by labrys** [guessit-io/guessit#258]
Running a scrape of rarbg's rss feed, with no filters on types of results, and processing all names with guessit 2.0rc7 and limiting output to only those with a country match: 
##### Total unique filenames with country: 88
- US: 68
  - All matches correct
- GB: 12
  - All matches correct
- CG: 4
  - `Congo.The.Grand.Inga.Project.2013.1080p.BluRay.x264-OBiTS`
  - `Congo.The.Grand.Inga.Project.2013.BRRip.XviD.MP3-RARBG`
  - `Congo.The.Grand.Inga.Project.2013.720p.BluRay.H264.AAC-RARBG`
  - `Congo.The.Grand.Inga.Project.2013.1080p.BluRay.H264.AAC-RARBG`
  - Incorrect matches: name in title
- CN: 1
  - `BBC The Story of China 1 of 6 - Ancestors CC HDTV x264 AC3 2.0 720p mkv`
  - Incorrect match: name in title
- RE: 1 
  - `Re-Loader Activator v2.2 FINAL (Windows &amp; Office Activator)  [TechTools]`
  - Incorrect match but not a video file 
- RO: 1
  - `PlayboyPlus.com_16.01.23.Eleni.Corfiate.Playboy.Romania.XXX.iMAGESET-OHRLY`
  - Correct, regional publication and not even a video
- VC: 1
  - `InDefinitely.Maybe.2008.1080p.EUR.BluRay.VC-1.DTS-HD.MA.5.1-FGT`
  - Incorrect match: [VC-1](https://en.wikipedia.org/wiki/VC-1)

log https://gist.github.com/labrys/8d9c5f26a095e40d9162

**Comment by ratoaq2** [comment]
Fixed by #476
