### ISSUE TITLE
ReadTheDocs are not build

### ISSUE THREAD

**Issue by Toilal** [guessit-io/guessit#262]
Hi @wackou, 

I think ReadTheDocs doesn't build since we have moved to the new repository URL. 

Could you give me access to the guessit project on ReadTheDocs so I can manage it and launch docs build manually if required ?

**Comment by wackou** [comment]
I updated the base URL of ReadTheDocs to point to the new repo, docs are properly built now. I also added you as maintainer for the ReadTheDocs project.
