### ISSUE TITLE
bad guess GERMAN AC3D

### ISSUE THREAD

**Issue by kecksk0enig** [guessit-io/guessit#269]
I have multiple badguesses containing audiocodec AC3D
and Wrong/no language detection (GERMAN)
attached one example.

For: Das.Appartement.GERMAN.AC3D.DL.720p.BluRay.x264-TVP
GuessIt found: {
    "title": "Das Appartement GERMAN AC3D", 
    "language": "Multiple languages", 
    "screen_size": "720p", 
    "format": "BluRay", 
    "video_codec": "h264", 
    "release_group": "TVP", 
    "type": "movie"
}

**Comment by Toilal** [comment]
Is AC3D a synonym for AC3 ?

**Comment by kecksk0enig** [comment]
yes it is a custom language AC3 Dubbed on the image

**Comment by Toilal** [comment]
And what does DL mean in this case ? Is this Dual Langage ?

**Comment by Toilal** [comment]
DL is recognized as Dual Langage, so GERMAN is not grabed as the langage and stay in the title. This is the expected behaviour. But real question is : what is the DL in this release name ?

**Comment by Toilal** [comment]
But maybe we would add a rule for GERMAN to be taken anywhen as a language, because it's uppercase.

**Comment by kecksk0enig** [comment]
I can confirm it is dual language so DL is correct.
Uppercase GERMAN could also be part of "GERMAN.SUBBED" or "custom.subbed.GERMAN"
like:
Homeland.S05E11.Our.Man.in.Damascus.German.Custom.Subbed.720p.HDTV.x264.iNTERNAL-BaCKToRG

Also there are many files named like:
Hyena.Road.2015.German.1080p.DL.DTSHD.Bluray.x264-pmHD
so upercase GERMAN would not get detected.

However  "German" is no often used title of movies/Series:
http://www.imdb.com/find?q=GERMAN&s=tt&exact=true&ref_=fn_tt_ex

So would be feasible to add German as language .

Thanks for your feedback

**Comment by Toilal** [comment]
Thanks for those examples.

```Hyena.Road.2015.German.1080p.DL.DTSHD.Bluray.x264-pmHD``` is detected properly because the year 2015 clearly split title from the rest.

```Homeland.S05E11.Our.Man.in.Damascus.German.Sub.720p.HDTV.x264.iNTERNAL-BaCKToRG``` is also guessed properly. But I need to had ```Subbed```, ```Custom Sub``` and ```Custom Subbed``` as markers for subtitles.

Those changes + considering UPPERCASE country in a non uppercase Title as the country and note beloging to the title, and we'll be OK for this issue I think.

**Comment by Toilal** [comment]
All cases are now working properly with latest master.
