### ISSUE TITLE
Make implicit option default behavior

### ISSUE THREAD

**Issue by labrys** [guessit-io/guessit#274]
guessit: 2.04
python: 2.7.11

When guessing a name with multiple `other` properties, guessit only matches the first.

``` python
>>> guessit("Show.Name.HR.WS.PDTV")
MatchesDict([('title', 'Show Name'), ('other', 'HR'), ('format', 'DVB'), ('type', 'movie')])
```

I would expect it to handle like seasons and episodes, returning a list if more than one match.

**Comment by Toilal** [comment]
In fact, it doesn't work with list of episode either. You have to enable implicit option for the API to behave like in command line ...

```python
>>> guessit("Show.Name.HR.WS.S02E05-06.PDTV", {'implicit': True})
MatchesDict([('title', 'Show Name'), ('other', ['HR', 'WideScreen']), ('season', 2), ('episode', [5, 6]), ('format', 'DVB'), ('type', 'episode')])
```

But I think I have to document this somewhere ...

**Comment by labrys** [comment]
@Toilal is there a way to enable this globally or should it be passed as an argument to each call?

**Comment by Diaoul** [comment]
Shouldn't it be default behavior?

**Comment by Toilal** [comment]
@Diaoul: Yes I think it should be the default behavior ...

@labrys: at each call.

**Comment by Toilal** [comment]
I think i'll reverse this `implicit=True` option to `explicit=False`. 

So it will be easy to migrate for people relying of the actual default behavior, and API will be consistent with command line version. People wanting the current behavior would be able to enable it by passing `explicit=True`.

**Comment by Toilal** [comment]
I move this to milestone 3.0 because it's a breaking change.

**Comment by Toilal** [comment]
Maybe guessit 3.x could return always list, even when a single value is found.

**Comment by Toilal** [comment]
@labrys

On MatchesDict object, you have `values_list` property that exactly do what you want. It gives a dict where each value is a list, even when a single value is found.

```python
>>> guessit.guessit("Show.Name.HR.WS.PDTV").values_list
defaultdict(<class 'list'>, {'title': ['Show Name'], 'other': ['HR', 'WideScreen'], 'format': ['DVB'], 'type': ['movie']})
```

**Comment by Toilal** [comment]
This is now default behavior.
