### ISSUE TITLE
Passing folder name title not filename title. 

### ISSUE THREAD

**Issue by fernandog** [guessit-io/guessit#275]
Passing file with folder name almost the same as filename:

``` bash
For: /downloaded/Marvels.Agent.Carter.S02E05.The.Atomic.Job.1080p.WEB-DL.DD5.1.H264-Coo7[rartv]/
Marvel's.Agent.Carter.S02E05.The.Atomic.Job.1080p.WEB-DL.DD5.1.H.264-Coo7.mkv
GuessIt found: {
    "title": "Marvels Agent Carter",
    "season": 2,
    "episode": 5,
    "episode_title": "The Atomic Job",
    "screen_size": "1080p",
    "format": "WEB-DL",
    "audio_codec": "DolbyDigital",
    "audio_channels": "5.1",
    "video_codec": "h264",
    "release_group": "Coo7[rartv]",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
```

Passing filename outside that folder:

``` bash
For: /downloaded/Marvel's.Agent.Carter.S02E05.The.Atomic.Job.1080p.WEB-DL.DD5.1.H.264-Coo7.mkv
GuessIt found: {
    "title": "Marvel's Agent Carter",
    "season": 2,
    "episode": 5,
    "episode_title": "The Atomic Job",
    "screen_size": "1080p",
    "format": "WEB-DL",
    "audio_codec": "DolbyDigital",
    "audio_channels": "5.1",
    "video_codec": "h264",
    "release_group": "Coo7",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}

```

@Diaoul @Labrys

**Comment by labrys** [comment]
It appears to be trying everything in LTR order.  Splitting filename out and trying it first and filling in additional information from the path afterwards might provide more consistent results.  E.g. the equivalent of guessit(path).update(guessit(filename))

**Comment by Toilal** [comment]
In this case, guessit 2 now has a clear rule (thought to fix #190): 

If same matches are found in multiple path elements, guessit will keep results from the part that contains the highest attributes count. 

In guessit 1.x, there was a confidence indice. it's been replaced with those kind of rule. path elements with greater count of properties are considered as more confident than path elements with less count of properties.

For example, removing the episode title from directory will build results from filename only ...

```
For: /downloaded/Marvels.Agent.Carter.S02E05.1080p.WEB-DL.DD5.1.H264-Coo7[rartv]/Marvel's.Agent.Carter.S02E06.The.Atomic.Job.1080p.WEB-DL.DD5.1.H.264-Coo7.mkv
GuessIt found: {
    "season": 2,
    "screen_size": "1080p",
    "format": "WEB-DL",
    "audio_codec": "DolbyDigital",
    "audio_channels": "5.1",
    "video_codec": "h264",
    "title": "Marvel's Agent Carter",
    "episode": 6,
    "episode_title": "The Atomic Job",
    "release_group": "Coo7",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

Reverse, if filename has less properties count, only folder will matter.

```
For: /downloaded/Marvels.Agent.Carter.S02E05.The.Atomic.Job.1080p.WEB-DL.DD5.1.H264-Coo7[rartv]/Marvel's.Agent.Carter.S02E06.The.Atomic.Job.1080p.DD5.1.H.264-Coo7.mkv
GuessIt found: {
    "title": "Marvels Agent Carter",
    "season": 2,
    "episode": 5,
    "episode_title": "The Atomic Job",
    "screen_size": "1080p",
    "format": "WEB-DL",
    "audio_codec": "DolbyDigital",
    "audio_channels": "5.1",
    "video_codec": "h264",
    "release_group": "Coo7[rartv]",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

In the case of the issue, both paths has the same count, so the left one (directory) is kept only.

Note that `container` and mimetype are excluded from those computations.

**Comment by labrys** [comment]
While I understand the reasoning for this, and for the most part it seems sound, I think the filename should probably override the path as folders are usually a generalization of the content within.

**Comment by ratoaq2** [comment]
I just want to add an important case:
- The folder contains season or episode range and
- The filename is only about 1 or 2 episodes

e.g.: `/Show.Name.S01E01-S01E12.(Complete).HDTV.720p.x264-GROUP/Show.Name.S01E01.HDTV.720p.x264-GROUP.mkv`


Right now I can't run guessit to check it out, but the folder name has all the properties that the filename has, plus the `other: Complete`. But what's expected in this case is to use the season and episode of the file (which is more specific).

IMO, in case of conflict between seasn/episodes numbers with season/episodes ranges, the more specific ones should take precedence

On a small note, I now that right now the range in the example doesn't work in guessit 2.0.5 as expected, but it doesn't invalidate the example.

**Comment by fernandog** [comment]
@ratoaq2 what changed after this? what should we do about this?

**Comment by fernandog** [comment]
thanks!
