### ISSUE TITLE
Invalid guess when `season` is in another language

### ISSUE THREAD

**Issue by labrys** [guessit-io/guessit#277]
If the word season is in another language (e.g. Seizon) it is not detected

``` python
>>> guessit('Vikings.Seizoen.4.1080p.Web.NLsubs')
MatchesDict([('title', 'Vikings Seizoen 4'), ('screen_size', '1080p'), ('format', 'WEB-DL'), ('release_group', 'NLsubs'), ('type', 'movie')])
>>> guessit('Vikings.Season.4.1080p.Web.NLsubs')
MatchesDict([('title', 'Vikings'), ('season', 4), ('screen_size', '1080p'), ('format', 'WEB-DL'), ('release_group', 'NLsubs'), ('type', 'episode')])
```

**Comment by Toilal** [comment]
Please provide a list of all words/language we could support. Same for
episode.
Le 21 févr. 2016 18:45, "Labrys of Knossos" <notifications@github.com> a
écrit :

**Comment by labrys** [comment]
This will have to be a dynamic list of course, but I'll start putting one together... one instance that comes to mind that may pose an issue is that Season is Series in the UK.

**Comment by ratoaq2** [comment]
Spanish and Portuguese: 
- Season = Temporada
- Seasons = Temporadas

Spanish
- Episode = Episodio
- Episodes = Episodios
- Chapter = Capitulo (Cap - abbreviated)

Portuguese:
- Episode = Episódio
- Episodes = Episódios
- Chapter = Capítulo 


And some examples
```
guessit 2.0.5
guessit "American.Crime.-.Temporada.1.720p.HDTV.x264[Cap.102]SPANISH.AUDIO-NEWPCT"
For: American.Crime.-.Temporada.1.720p.HDTV.x264[Cap.102]SPANISH.AUDIO-NEWPCT
GuessIt found: {
    "title": "American Crime", 
    "alternative_title": "Temporada 1", 
    "screen_size": "720p", 
    "format": "HDTV", 
    "video_codec": "h264", 
    "season": 1, 
    "episode": 2, 
    "language": "Spanish", 
    "episode_title": "AUDIO-NEWPCT", 
    "type": "episode"
}
```
when enabling implicit=True, then it adds the season 1 to the episode list as well.

**Comment by ratoaq2** [comment]
Season in dutch is handled by #420.

But it's still not possible to have them configurable, not yet.

**Comment by Toilal** [comment]
It seems to be supported now in configuration file.

**Comment by ratoaq2** [comment]
I'm still alive 😬
