### ISSUE TITLE
Regression for titles containing dots

### ISSUE THREAD

**Issue by Diaoul** [guessit-io/guessit#278]
v1.0.3
```
$ guessit 'Marvels.Agents.of.S.H.I.E.L.D.S02E06.720p.HDTV.x264-KILLERS.srt'
For: Marvels.Agents.of.S.H.I.E.L.D.S02E06.720p.HDTV.x264-KILLERS.srt
GuessIt found: {
    [1.00] "mimetype": "text/plain", 
    [0.60] "episodeNumber": 6, 
    [0.60] "videoCodec": "h264", 
    [1.00] "container": "srt", 
    [0.60] "format": "HDTV", 
    [0.42] "series": "Marvels Agents of S.H.I.E.L.D.", 
    [0.60] "releaseGroup": "KILLERS", 
    [0.60] "screenSize": "720p", 
    [0.60] "season": 2, 
    [1.00] "type": "episodesubtitle"
}
```

v2.0.4
```
$ guessit 'Marvels.Agents.of.S.H.I.E.L.D.S02E06.720p.HDTV.x264-KILLERS.srt'
For: Marvels.Agents.of.S.H.I.E.L.D.S02E06.720p.HDTV.x264-KILLERS.srt
GuessIt found: {
    "title": "Marvels Agents of S H I E L D", 
    "season": 2, 
    "episode": 6, 
    "screen_size": "720p", 
    "format": "HDTV", 
    "video_codec": "h264", 
    "release_group": "KILLERS", 
    "container": "srt", 
    "mimetype": "text/plain", 
    "type": "episode"
}
```

**Comment by Diaoul** [comment]
I'm a bit stuck here, `Marvels Agents of S.H.I.E.L.D.` is found on TVDB but `Marvels Agents of S H I E L D` isn't so I cannot grab the correct information from other sources.
Do you think you can implement this soon? I think the rule is something like `[A-Z].([A-Z]|$)` means keep the dot.
I can make a PR if you can point me how to implement this or if there is any similar rule in place I can base my work on.

**Comment by Toilal** [comment]
I'm sorry I've not time to fix it myself, but I think with the following tips, you will be able to provide a PR soon :)

1) [title.py](https://github.com/guessit-io/guessit/blob/master/guessit/rules/properties/title.py#L169-L171) is responsible to find title froms "holes". "hole" is a filepart that doesn't match anything, so it's a candidate for the title.
2) Those "hole matches" have a formatter function defined, here `formatter=formatters(cleanup, reorder_title)`. It's a chain of 2 formatter functions, `cleanup` and `reorder_title`.
3) You should implement a more cleaver [cleanup](https://github.com/guessit-io/guessit/blob/master/guessit/rules/common/formatters.py#L20-L30) function for dots to be kept in the case of `S.H.I.E.L.D`. But it should be as efficient as possible though.
4) Maybe [cleanup](https://github.com/guessit-io/guessit/blob/master/guessit/rules/common/formatters.py#L20-L30) function is used elsewhere, i'm not sure about that ... If it's used elsewhere, you should create a new function, something like `title_cleanup` would be ok.

Good luck, feel free to ping me when your PR is ready. Thanks :)

**Comment by Toilal** [comment]
I'll try to do it this week end.

**Comment by Diaoul** [comment]
Awesome, thanks!

**Comment by ratoaq2** [comment]
The same issue still happens with the Series `11.22.63`:

```
+-------------------------------------------------------+
+                   GuessIt 2.0.5                       +
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|     https://github.com/guessit-io/guessit/issues.     |
+-------------------------------------------------------+

guessit "11.22.63.-.S01E06.HDTV.x264.MKV.720p.HD"
For: 11.22.63.-.S01E06.HDTV.x264.MKV.720p.HD
GuessIt found: {
    "title": "11 22 63", 
    "season": 1, 
    "episode": 6, 
    "format": "HDTV", 
    "video_codec": "h264", 
    "container": "MKV", 
    "screen_size": "720p", 
    "other": "HD", 
    "type": "episode"
}
```

**Comment by Toilal** [comment]
@ratoaq2 I won't fix this one. Dots will remain only for acronyms like S.H.I.E.L.D (1 letter words).
