### ISSUE TITLE
Advanced option with API

### ISSUE THREAD

**Issue by flatgreen** [guessit-io/guessit#279]
Hello,

With the API, how can have the "advanced" informations ? I tried :
guessit ("nameserie.S02E04.720p.x264-river.mkv", "- a")
and I get:
MatchesDict ([('title', <nameserie: (0, 10) + name = title + tags = ['title']>) ('season' <2 (11, 13) + name = season + tags = [ 'SxxExx']>) ( 'episode', <4 (14, 16) + name = episode + tags = [ 'SxxExx']>) ( 'screen_size' <720p (17, 21) + name = screen_size>) ( 'video_codec' <h264 (22, 26) + name = video_codec>) ( 'release_group' <river (26, 32) + name = release_group + tags = ['scene ']>) (' container '<mkv (32, 36) + name = container + tags = [' extension ',' extension ',' video ']>) (' type ', <episode :( 36, 36) + name = type>)])

How to get the fields "raw" ?

**Comment by labrys** [comment]
@flatgreen It can be treated just like a dictionary.  e.g.:
```python
>>> result = guessit ("nameserie.S02E04.720p.x264-river.mkv", "-a")
>>> result['title']
<nameserie:(0, 10)+name=title+tags=['title']>>>> result.get('title')
>>> result.pop('title')
<nameserie:(0, 10)+name=title+tags=['title']>
>>> result['title']
>>>
```
I hope this answered your questions
also I noticed you had a space between the `-` and the `a`

**Comment by flatgreen** [comment]
OK (and no problème with the space ...)
with :

```
>>> result['video_codec']
<h264:(22, 26)+name=video_codec>

```
This is not the "raw" entry (x264). Is it possible to access it ?

**Comment by labrys** [comment]
The start and end of the match is listed there as 22, 26
You can access it as follows (there may be a better way, but im just now starting to dig into the advanced section):
```python
>>> result = guessit ("nameserie.S02E04.720p.x264-river.mkv", "-a")
>>> codec = result['video_codec']
>>> codec.input_string[codec.start, codec.end]
'x264'
```

**Comment by flatgreen** [comment]
Super, thank you !

**Comment by labrys** [comment]
@flatgreen I knew I was forgetting something:
```python
>>> result = guessit ("nameserie.S02E04.720p.x264-river.mkv", "-a")
>>> codec = result['video_codec']
>>> codec.raw
'x264'
``````
Much nicer! :grinning:
