### ISSUE TITLE
Using command line options as argument

### ISSUE THREAD

**Issue by mayankgautam** [guessit-io/guessit#281]
In the documentation, it has been mentioned that Command line options can be given as dict or string to the second argument. 

I wanted the output in json format but it is not clear to me how to specify it as the second argument. 

Please give me an example regarding the usage of command line arguments.

Thanks and Regards,
MG

**Comment by miigotu** [comment]
In guessit2, it seems -j is the argument you want.

**Comment by Toilal** [comment]
the guessit api doesn't support json encoding, it only returns a MatchDict object (which is a dict).

To encode the output in json, you can use this code.

```python
from guessit.jsonutils import GuessitEncoder
from guessit import guessit

guess = guessit('.....')

guess_json = json.dumps(guess, cls=GuessitEncoder, ensure_ascii=False)
```

**Comment by miigotu** [comment]
I thought he was asking about actual command line arguments =p
