### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by labrys** [guessit-io/guessit#283]
The properties listed in the [docs](http://guessit.readthedocs.org/en/latest/properties.html#properties) don't match the ones reported by `guessit -p` (using 2.1.0.dev0)

Listed in docs but not reported by `guessit -p':
* `alternative_title`
* `mimetype`
* `series`

Reported by `guessit -p` but not listed in docs:
* `film_title`
* `count`

**Comment by Toilal** [comment]
:+1: Thanks ! I don't have much free time for now, but i'll try to fix this in the next few weeks.
