### ISSUE TITLE
Multi-Episode detection

### ISSUE THREAD

**Issue by Con7e** [guessit-io/guessit#285]
Hello!

Would it be possible for guessit to correctly display episode information in the case in which we have a multi-episode "naming" of the file?
e.g:

`The Office S06E17E18 720p BluRay DTS x264-CtrlHD.mkv`

This currently gives the following result:

> ['title', 'The Office']
> ['season', 6]
> ['episode', 17]
> ['screen_size', '720p']
> ['format', 'BluRay']
> ['audio_codec', 'DTS']
> ['video_codec', 'h264']
> ['release_group', 'CtrlHD']
> ['container', 'mkv']
> ['type', 'episode']

**Comment by Toilal** [comment]
It actually works.

```
guessit "The Office S06E17E18 720p BluRay DTS x264-CtrlHD.mkv"
For: The Office S06E17E18 720p BluRay DTS x264-CtrlHD.mkv
GuessIt found: {
    "title": "The Office",
    "season": 6,
    "episode": [
        17,
        18
    ],
    "screen_size": "720p",
    "format": "BluRay",
    "audio_codec": "DTS",
    "video_codec": "h264",
    "release_group": "CtrlHD",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

But if you are using the API, you have to pass ```implicit=True``` option.

[CLI has this option forced](https://github.com/guessit-io/guessit/blob/28b67896fc26a0473d5738526a45d4b4003e6c80/guessit/__main__.py#L29-L32)

**Comment by Con7e** [comment]
Hello,

First, thanks for this! Second, are there any other changes made when I use that option in regards to how guessit guesses ?

**Comment by Toilal** [comment]
I think it's the only one.

**Comment by Con7e** [comment]
I thought it was enough to say `guessit.guessit("The Office S06E17E18 720p BluRay DTS x264-CtrlHD.mkv", implicit=True)` but it isn't. Would you mind telling me where should I put this in the API?

**Comment by Con7e** [comment]
Found it. Apparently need to use a dict:

`print guessit.guessit("The Office S06E17E18 720p BluRay DTS x264-CtrlHD.mkv", options={"implicit":True})`

Thanks a lot @Toilal
