### ISSUE TITLE
Not detecting episode number

### ISSUE THREAD

**Issue by fernandog** [guessit-io/guessit#286]
```
 guessit --version
+-------------------------------------------------------+
+                   GuessIt 2.0.5                       +
+-------------------------------------------------------+

```

```
guessit "Black.Sails.S02E02.X.1080p.WEB-DL.DD5.1.H.264-BS.mkv"
For: Black.Sails.S02E02.X.1080p.WEB-DL.DD5.1.H.264-BS.mkv
GuessIt found: {
    "title": "Black Sails",
    "season": 2,
    "screen_size": "1080p",
    "format": "WEB-DL",
    "audio_codec": "DolbyDigital",
    "audio_channels": "5.1",
    "video_codec": "h264",
    "release_group": "BS",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

**Comment by fernandog** [comment]
https://github.com/pymedusa/SickRage/issues/403

**Comment by Toilal** [comment]
The conflict occurs with such episode patterns : 01x02x03. 

In this case, it catch `episode` 2 and 1080, and those matches are finally cropped because of `screen_size` gets priority while resolving conflict. 

I'm still investigating, but this case is hard to fix without breaking anything else.

**Comment by fernandog** [comment]
@Toilal sorry if is a dumb question but to match 01x02x03 shouldn't it check for mutiple x[0-9]* ?

**Comment by Toilal** [comment]
Patterns for season/episode are defined using [rebulk](https://github.com/Toilal/rebulk) in this file : https://github.com/guessit-io/guessit/blob/61303fa009ff3b17cd91be7a18fcccec8642d027/guessit/rules/properties/episodes.py. 

Basically, all defined patterns are checked on the whole string, and then rebulk runs a validation phase, a conflict solving phase and a rules phase to keep only valid matches, remove duplicates, etc. 

So the whole thing is not always as simple as it seems.

But anyway, thank you for reporting those edge case bugs !

**Comment by fernandog** [comment]
hey @Toilal manage to find a fix for this? thanks!

**Comment by Toilal** [comment]
Yes, it's almost there.

**Comment by fernandog** [comment]
hey @Toilal any news on this? sorry asking again

**Comment by Toilal** [comment]
Sorry for delay, I have few time for dev at the moment, and this issue is really hard to solve.

I've already spent some hours on it, but still can't find a proper solution. It's also related to underlying rebulk library.

It's still on top priority, but sadly I can't tell you when it will be fixed :(

**Comment by Toilal** [comment]
I've finally fixed this issue ! X will not be detected as title, and a title should be at least 3 characters long.
