### ISSUE TITLE
Incorrect guess for season/episode ranges

### ISSUE THREAD

**Issue by labrys** [guessit-io/guessit#287]
Guessit 2.0.5
```python
>>> guessit('show s01-s04', options=dict(implicit=True))['season']
[1, 4]
>>> guessit('show s01e03-e05', options=dict(implicit=True))['season']
[3, 5]
```
Since a dash separation in a range implies all numbers within that range, I would expect this to return all seasons/episodes within that range.

**Comment by Toilal** [comment]
It's the expected behavior for guessit. For guessit to guess range, `s` and `e` should not appear before the second number. You can still post-process the guessit output to generate intermediate values.

**Comment by labrys** [comment]
post processing is how i plan to implement it for now, but I'm curious as to why its expected behaviour. Most people that see that type of numbering would expect it to include the intermediate values to be included (and indeed most multi-episode names do reflect that).

**Comment by Toilal** [comment]
I'll change the behavior in `2.1.0`. 

I agree it's not the expected behaviour in this case.

**Comment by ratoaq2** [comment]
Just to share a different scenario:

`guessit 2.0.5`

```
guessit -t episode "My.Name.Is.Earl.S01E01-S01E21.SWE-SUB"
For: My.Name.Is.Earl.S01E01-S01E21.SWE-SUB
GuessIt found: {
    "title": "My Name Is Earl", 
    "season": 1, 
    "episode": [
        1, 
        21
    ], 
    "subtitle_language": "Swedish", 
    "type": "episode"
}
```

**Comment by ratoaq2** [comment]
Please, don't be mad at me.

This fixed a lot of my scenarios, but there are some corner cases still failing. I can share them here:

```
guessit "Show.Name.Season.4.Episodes.1-12"
For: Show.Name.Season.4.Episodes.1-12
GuessIt found: {
    "title": "Show Name", 
    "season": 4, 
    "episode": 1, 
    "episode_count": 12, 
    "type": "episode"
}


guessit "Show.Name.S03E21.22.FASTSUB.VOSTFR.HDTV.XviD.GROUP"
For: Show.Name.S03E21.22.FASTSUB.VOSTFR.HDTV.XviD.GROUP
GuessIt found: {
    "title": "Show Name", 
    "season": 3, 
    "episode": 21, 
    "episode_title": "22", 
    "other": "Fastsub", 
    "subtitle_language": "French", 
    "format": "HDTV", 
    "video_codec": "XviD", 
    "release_group": "GROUP", 
    "type": "episode"
}


For: Show.Name.Season.1~3.Mp4.1080p
GuessIt found: {
    "title": "Show Name", 
    "season": 1, 
    "episode_title": "3", 
    "container": "MP4", 
    "screen_size": "1080p", 
    "type": "episode"
}


For: show name s01.to.s04
GuessIt found: {
    "title": "show name", 
    "season": [
        1, 
        4
    ], 
    "episode_title": "to", 
    "type": "episode"
}
```

I don't know if you prefer to have them in a separate issue,

**Comment by Toilal** [comment]
Yes please create another issue :) You really help by testing guessit and opening issue, keep on :)

**Comment by Toilal** [comment]
I just fixed the example with ~.
