### ISSUE TITLE
dateutil 2.5.3

### ISSUE THREAD

**Issue by stevezau** [guessit-io/guessit#291]
Hey,

We just forced flexget to be dateutil>=2.5.3 and released it's causing conflicts with guessit as you have <2.5.2.

Any chance you will be changing to 2.5.3?

**Comment by Toilal** [comment]
It seems you also haved locked the version to 2.5.2 in flexget. I think it's the best choice for now.

We had some discussion with author of dateutil module, and changes introduced in 2.5.3 will be refactored in 2.6.0 to support finer control of date, month and year ordering.

So I guess I'll have to wait for this version to be released.
