### ISSUE TITLE
Guessit flags Series as invalid Guessit

### ISSUE THREAD

**Issue by crawln45** [guessit-io/guessit#292]
Seems we are having issues when values are changed. I'm not exactly sure why. Would like your expertise if I may. Issue is here https://github.com/Flexget/Flexget/issues/1098

**Comment by effemmeffe** [comment]
Same here: https://github.com/Flexget/Flexget/issues/1159
They told me to report it in this repository.

**Comment by ratoaq2** [comment]
This seems to be already fixed. Otherwise, please reopen it
