### ISSUE TITLE
pip install guessit1.0.2 error

### ISSUE THREAD

**Issue by thejacobsons** [guessit-io/guessit#312]
I am trying to install guessit1.0.2 and get the following error. I need this version for other software I am using.

C:\WINDOWS\system32>pip install guessit1.0.2
Downloading/unpacking guessit1.0.2
  Could not find any downloads that satisfy the requirement guessit1.0.2
Cleaning up...
No distributions at all found for guessit1.0.2
Storing debug log for failure in C:\Users\me\pip\pip.log

[pip.docx](https://github.com/guessit-io/guessit/files/324557/pip.docx)

**Comment by Toilal** [comment]
pip install "guessit<2" should work.
