### ISSUE TITLE
[Feature] Detect hard coded subs (HC)

### ISSUE THREAD

**Issue by ratoaq2** [guessit-io/guessit#318]
Some releases have HC to flag hard-coded subtitles.

e.g.:
`Show.Name.S06E16.HC.SWESUB.HDTV.x264.mp4`

This means hard-coded swedish subtitles.

Probably adding another value to `other` property should be enough.
- Note: In this case, SWESUB is detected as Swahili (ISO 639-1 = sw) instead of Swedish (ISO 639-3 = swe)

**Comment by 2ge** [comment]
+1

**Comment by ratoaq2** [comment]
Fixed by #407
