### ISSUE TITLE
Multiple formats for a single release_name

### ISSUE THREAD

**Issue by ratoaq2** [guessit-io/guessit#327]
`guessit 2.0.5` or latest development commit `67b8ac712cb28af6b2e31a8b11a47735b65d59c4`

I was unsure if this was an guessit issue or a subliminal issue, but considering that for a single video, there should be 1 format, I'm considering it a guessit issue.

```
guessit -t episode "Mr.Robot.S02E01.eps2.0.unm4sk-pt1.tc.1080p.WEB-DL.DD5.1.H264-NTb[rarbg]"
For: Mr.Robot.S02E01.eps2.0.unm4sk-pt1.tc.1080p.WEB-DL.DD5.1.H264-NTb[rarbg]
GuessIt found: {
    "title": "Mr Robot", 
    "season": 2, 
    "episode": 1, 
    "episode_title": "eps2 0 unm4sk", 
    "part": 1, 
    "format": [
        "Telecine", 
        "WEB-DL"
    ], 
    "screen_size": "1080p", 
    "audio_codec": "DolbyDigital", 
    "audio_channels": "5.1", 
    "video_codec": "h264", 
    "release_group": "NTb[rarbg]", 
    "type": "episode"
}
```

Because the episode name has `.tc.`, guessit guess 2 formats for it.

In subliminal, we get the following exception:
```
  File "/folder/myscript/subtitles.py", line 326, in download_best_subs
    for s in subtitles_list], key=operator.itemgetter(1), reverse=True)
  File "/folder/subliminal/score.py", line 88, in compute_score
    matches = subtitle.get_matches(video)
  File "/folder/subliminal/providers/legendastv.py", line 147, in get_matches
    matches |= guess_matches(video, guessit(self.archive.name, {'type': self.type}))
  File "/folder/subliminal/subtitle.py", line 233, in guess_matches
    if video.format and 'format' in guess and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'
```

This raises some questions:
- Should guessit ensure that only one format is returned?
- Should subliminal handle multiple formats at all? (@Diaoul)

**Comment by ratoaq2** [comment]
Just a side note.
As I said: a single video should have 1 format; but release names could refer to a season pack or multiple episodes, then we could have more than 1 format.

**Comment by Toilal** [comment]
It's related to #274, but guessit should return both formats in this case.

Subliminal (and others) should check if value is a list and handle multiple values in this case.

Maybe python 3.x will return everything as lists, but as it's a breaking change I can't change this behavior before next major release.

**Comment by Diaoul** [comment]
Can you list the properties that can be a list or a single value?
