### ISSUE TITLE
python2-dateutil<2.5.2 depend is breaking other packages

### ISSUE THREAD

**Issue by hawkway** [guessit-io/guessit#329]
other packages require a more recent version of dateutl, is there any way we can reevaluate the state of the version of dateutil working for the project?

 File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-dateutil>=2.5.2' distribution was not found and is required by FlexGet

https://aur.archlinux.org/packages/flexget/

**Comment by Toilal** [comment]
It cause technical problems at the moment, but i'll try to find a proper solution.

**Comment by hawkway** [comment]
I saw your original report/issue with the package when I started digging into it more. Is there anything I can do to help? I am a C# dev.

**Comment by Toilal** [comment]
It may be hard to solve such issue if you never write python code. But the idea is to create a fork, upgrade the dependency to latest release of python-dateutil (see setup.py) and then fix failing tests... 

But i'm not sure it's possible without actually forking python-dateutil too :(

**Comment by hawkway** [comment]
I can give it a shot and see how things go. I wrote ~1500 lines of python a little bit ago, but switched the project over to perl.

**Comment by bderrly** [comment]
@Toilal have you heard from the dateutil devs how long until they're ready to release an updated version that isn't breaking you and by proxy flexget?

**Comment by Toilal** [comment]
Yes, sorry about that.

I think i'll comment the failing tests and remove the dependency constraint on dateutil version. And then release a new guessit version. Hopefully this week.

**Comment by hawkway** [comment]
Thank you for the update, I have not had any time to look into this on my end. Sorry about that.

**Comment by Toilal** [comment]
I have found some code to make it works with both python 2.5.2 and 2.5.3, so i will release the dependency constraint :) Release coming soon.
