### ISSUE TITLE
audio_codec DolbyDigital and AC3 is the same thing

### ISSUE THREAD

**Issue by Toilal** [guessit-io/guessit#330]
It seems that `DolbyDigital` and `AC3` is actually the same codec, so guessit should return `AC3` instead of `DolbyDigital` when a DolbyDigital pattern is guessed.

Feel free to engage if you disagree :)

**Comment by ratoaq2** [comment]
+1

It would be a breaking change though.

**Comment by Toilal** [comment]
I won't consider this breaking because it touch only semantics of returned values. I don't think it would break anything for end users.

**Comment by VeNoMouS** [comment]
For my 2 cents, I think it should return AC3 if its labeled AC3

**Comment by ratoaq2** [comment]
@Toilal, what do you think? 
Could this be addressed on 2.1.3 or 2.2.x?
I could easily fix it, but I'm unsure if such change should come in 2.1.x releases

Looking at the open issues today, the important ones from my point of view are the ones that introduce some kind of breaking change, like `Make xyz consistent`,  the language / country detection, implicit as default behavior, and this one. 

What's your view on the next releases?

**Comment by Toilal** [comment]
First of all, thank you very much for maintaining guessit and fixing so many issues :)

I think I could release 2.1.3, and the you start working on 2.2.x with those breaking changes. Tell me when you are ready to release, and i'll do it shortly then ...

**Comment by ratoaq2** [comment]
That will be great. Thanks
