### ISSUE TITLE
Guessit does not identify Double episode containing files names such E01-E02

### ISSUE THREAD

**Issue by stampedeboss** [guessit-io/guessit#332]
Attempting to use guessit and it only identifies the first episode of a file that contains more than one.  File name such as TITLE.S01E01-E02.....

**Comment by Toilal** [comment]
Which version are you running.

Here, using master =>

```
For: TITLE.S01E01-E02.mkv
GuessIt found: {
    "title": "TITLE", 
    "season": 1, 
    "episode": [
        1, 
        2
    ], 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
```

Maybe you hit this issue #274 if you are using the python module, you have to enable the implicit option.

Reopen if you have any other question.
