### ISSUE TITLE
Regression for season and episode ranges

### ISSUE THREAD

**Issue by ratoaq2** [guessit-io/guessit#342]
Latest commit: 

```
commit a4fb2865d4b697397aa976388bbd0edf558a24fb
Author: Toilal <toilal.dev@gmail.com>
Date:   Mon Sep 19 23:35:26 2016 +0200

    Enhance episode/season range and sequence guessing

    Close #311
```

Expected: season: [1, 3, 4] and no episode

```
guessit.py -t episode "Show.Name.-.Season.1.3.4-.Mp4.1080p"
For: Show.Name.-.Season.1.3.4-.Mp4.1080p
GuessIt found: {
    "title": "Show Name", 
    "season": 1, 
    "episode": [
        3, 
        4
    ], 
    "container": "MP4", 
    "screen_size": "1080p", 
    "type": "episode"
}
```

Expected: season 2, episode 1 and episode_title: eps2 0 unm4sk'

```
guessit -t episode "Show.Name.S02E01.eps2.0.unm4sk-pt1.tc.1080p.WEB-DL.DD5.1.H264-GROUP.mkv"
For: Show.Name.S02E01.eps2.0.unm4sk-pt1.tc.1080p.WEB-DL.DD5.1.H264-GROUP.mkv
GuessIt found: {
    "title": "Show Name", 
    "season": 2, 
    "episode": 1, 
    "episode_title": "eps2", 
    "part": 1, 
    "format": [
        "Telecine", 
        "WEB-DL"
    ], 
    "screen_size": "1080p", 
    "audio_codec": "DolbyDigital", 
    "audio_channels": "5.1", 
    "video_codec": "h264", 
    "release_group": "GROUP", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
```

Expected: season 2, episode 6 and episode title: eps2 4 m4ster-s1ave aes

```
guessit -t episode "Show.Name.S02E06.eps2.4.m4ster-s1ave.aes.1080p.AMZN.WEBRip.DD5.1.x264-GROUP"
For: Show.Name.S02E06.eps2.4.m4ster-s1ave.aes.1080p.AMZN.WEBRip.DD5.1.x264-GROUP
GuessIt found: {
    "title": "Show Name", 
    "season": [
        2, 
        4, 
        1
    ], 
    "episode": 6, 
    "episode_title": "eps2", 
    "screen_size": "1080p", 
    "format": "WEBRip", 
    "audio_codec": "DolbyDigital", 
    "audio_channels": "5.1", 
    "video_codec": "h264", 
    "release_group": "GROUP", 
    "type": "episode"
}
```

2nd and 3rd scenario are episode titles from `Mr. Robot`

**Comment by Toilal** [comment]
I think the episode and season range validation could be simplified by using new rebulk feature `chain_breaker`.

I used it [here](https://github.com/guessit-io/guessit/blob/243f8f83fc402757dff97ec70d622a68bbadcb5d/guessit/rules/properties/episodes.py#L33-L50), it works like a charm and should be more performant than actual post process Rules for range validation.

We should find all those rules, and replace them with `chain_breaker` functions.

chain_breaker function is invoked for each part added to the chain ...

For example, when parsing S01E02-03-04-05, it's invoked with 5 times, 1st time with [S01], 2nd with [S01, E02], 3rd with [S01, E02, E03], ... If the chain_breaker function returns False, the last element is not added in the chain result, and chain parsing stops there.

**Comment by Toilal** [comment]
That beeing said, the actual implementation is clearly documented, and 1st case is the expected behavior:

```
        Validator for season list. They should be in natural order to be validated.
        episode/season separated by a weak discrete separator should be consecutive, unless a strong discrete separator
        or a range separator is present in the chain (1.3&5 is valid, but 1.3-5 is not valid and 1.3.5 is not valid)
```

But this rule can change I you find a solid and more natural rule.

**Comment by ratoaq2** [comment]
The main issue with having that rule "ordered and without gaps" is not about the rule itself, but the consequence. In this case `Show.Name.-.Season.1.3.4-.Mp4.1080p`, a multi season pack that refers to season 1, season 3 and season 4 is guessed as a double episode: season 1, episode 3 and 4.

I was able to update to latest guessit using a less strict rule (where gaps are allowed, but numbers should be ascending and separators should be the `simple ones`: like `.`).

The other 2 scenarios are related to `Mr. Robot` episode titles. They are tricky.
`eps2.0_unm4sk-pt1.tc`

`Mr.Robot.S02e01.eps2.0_unm4sk-pt1.tc`

Now with one of the latest rebulk fixes, there's an episode chain as well that wasn't detected before: `e01.eps2`

For these ones, I have no ideas. The main issue is not the episode title, but the additional episodes that are added to the guess result.

**Comment by ratoaq2** [comment]
About `Show.Name.-.Season.1.3.4-.Mp4.1080p` scenario.

Maybe the allowed gaps could be configurable. By default its value could be 0 (as of now) or even 1.
That will give us a possibility to have it strict or less strict.

Any thoughts?

**Comment by Toilal** [comment]
I think many things in guessit could be configurable

Maybe we could make those _discrete_ and _range_ separators configurable.

**Comment by ratoaq2** [comment]
Just to start a discussion on this topic:

There are things that we can't make easily configurable because they are required during rebulk rules setup. Other things are easy because they are needed during rule execution time (using the context). Other things happens during rule execution (expected titles, allowed languages, etc) that could be done only once when using guessit as a library in your app. Do you have any view on this?

What's your view about advanced settings? Are they going to be available only through config files? Or exposed via cli as well?

**Comment by ratoaq2** [comment]
@Toilal do you have an idea or suggestion on how to better access the configuration during "rebulk rules setup"?
