### ISSUE TITLE
AMZN in "other" field

### ISSUE THREAD

**Issue by OmgImAlexis** [guessit-io/guessit#344]
AMZN isn't being added to the other field similar to how Netflix is, for example in https://github.com/guessit-io/guessit/issues/248 and https://github.com/guessit-io/guessit/issues/117.

```
➜  ~ guessit "Better.Things.S01E02.Period.1080p.AMZN.WEBRip.DD5.1.x264-CasStudio.mkv" 
For: Better.Things.S01E02.Period.1080p.AMZN.WEBRip.DD5.1.x264-CasStudio.mkv
GuessIt found: {
    "title": "Better Things", 
    "season": 1, 
    "episode": 2, 
    "episode_title": "Period", 
    "screen_size": "1080p", 
    "format": "WEBRip", 
    "audio_codec": "DolbyDigital", 
    "audio_channels": "5.1", 
    "video_codec": "h264", 
    "release_group": "CasStudio", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
➜  ~ guessit "House.of.Cards.2013.S02E03.1080p.NF.WEBRip.DD5.1.x264-NTb.mkv"         
For: House.of.Cards.2013.S02E03.1080p.NF.WEBRip.DD5.1.x264-NTb.mkv
GuessIt found: {
    "title": "House of Cards", 
    "year": 2013, 
    "season": 2, 
    "episode": 3, 
    "screen_size": "1080p", 
    "other": "Netflix", 
    "format": "WEBRip", 
    "audio_codec": "DolbyDigital", 
    "audio_channels": "5.1", 
    "video_codec": "h264", 
    "release_group": "NTb", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
```

**Comment by Toilal** [comment]
Can you provide a list of others tags like those that could be added to the other detection ?

**Comment by duramato** [comment]
```The.Daily.Show.with.Trevor.Noah.2016.09.28.Reid.Hoffman.Extended.1080p.CC.WEBRip.AAC2.0.x264-monkee```
`CC` (Comedy central)
```Whose.Line.Is.It.Anyway.US.S12E20.Cheryl.Hines.720p.CW.WEBRip.AAC2.0.x264-monkee```
`CW` 
```Jimmy.Kimmel.Live.2016.09.27.J.K.Simmons.Action.Bronson.Air.720p.AMBC.WEBRip.AAC2.0.x264-monkee```
`AMBC`
```102.Minutes.That.Changed.America.15th.Anniversary.Edition.720p.HIST.WEBRip.AAC2.0.H.264-monkee```
`HIST`
```PBS.Specials.The.Kennedy.Center.Mark.Twain.Prize.2015.Eddie.Murphy10800p.PBS.WEBRip.AAC2.0.H264-monkee```
`PBS`
```Doug.Stanhope.2016.No.Place.Like.Home.1080p.SESO.WEBRip.AAC2.0.x264-monkee```
`SESO`
```
Deadliest.Catch.Dungeon.Cove.S01E03.Lost.at.Sea.720p.DISC.WEBRip.AAC2.0.x264-NTb
```
`DISC` (Discovery)
```Rio.Olympics.2016.08.18.Diving.Womens.10m.Finals.720p.iP.WEBRip.AAC2.0.H.264-monkee```
`iP` (iPlayer, if im not mistaken)
```Intervention.S15E18.Megan.720p.AE.WEBRip.AAC2.0.H.264-monkee```
`AE` 
```The.Eric.Andre.Show.S04E01.T.I.Abbey.Lee.Miller.1080p.AS.WEBRip.AAC2.0.H.264-monkee```
`AS` (Adult Swim)

```The.Late.Show.with.Stephen.Colbert.2016.05.10.Chloë.Grace.Moretz.Katie.Couric.Charlamagne.Tha.God.720p.CBS.WEBRip.AAC2.0.x264-monkee```

`CBS`
```NBA.2016.02.27.Golden.State.Warriors.vs.Oklahoma.City.Thunder.720p.NBA.WEBRip.AAC2.0.H.264-monkee```
`NBA`
```Road.To.The.NHL.Winter.Classic.S05E04.Canadiens.vs.Bruins.Part4.720p.EPIX.WEBRip.AAC2.0.H.264-monkee```
`EPIX`

```Saturday.Night.Live.S41E03.Tracy.Morgan.Demi.Lovato.720p.NBC.WEBRip.AAC2.0.x264-monkee```
`NBC`

**Comment by ratoaq2** [comment]
Why not having a specific field for network instead of adding all of them to `other` ?

If you allow me, I could create a PR and you could evaluate it.

**Comment by Toilal** [comment]
Would be great :)
