### ISSUE TITLE
Flexget & Guessit = slow

### ISSUE THREAD

**Issue by crack00r** [guessit-io/guessit#347]
maybe you could take a look in here, and add some performance tweaks
https://github.com/Flexget/Flexget/issues/1436

**Comment by Toilal** [comment]
Guessit is not designed to be fast. I made the choice to make it extendable and full of rules and patterns that make it guess most of possible filename formats from various scenes, but it comes with a performance cost and I'm sorry about that. 

For now, if you want better performance, you should stick to guessit internal parser. 

Algorithms attached in this thread seems interesting, i'll have a look, but i'm not sure it will come one day in guessit, and anyway it would require refactoring in guessit to somehow batch parsing requests. I'm not sure it's possible considering the actual Flexget architecture. 

Maybe other strategies could be used, like caching if some parsing requests are performed multiple times with the same input ? Is it the case ? Maybe we could compile some patterns from result of the previous requests to find next episodes from the same series faster for near future ? Not sure it's the guessit responsibility though, as we want to provide a parser that just magicaly works.

**Comment by Toilal** [comment]
I'll try to benchmark guessit performance through, and do some profiling to see bottlenecks.

**Comment by ratoaq2** [comment]
Just another feedback related to performance. 

We also use guessit embedded in our application. We have a predefined list of expected titles and expected groups defined as regexes. And we just call guessit.guessit with these lists. 

I know that for expected titles and expected groups compiles the expected regexes every single call

**Comment by Toilal** [comment]
python re module as an internal cache for this, but it would be better to explicitly compile patterns in guessit code, true.

**Comment by crack00r** [comment]
Any news on this?

**Comment by Toilal** [comment]
We have won about 50% performance gain with latest rebulk release on Python 3.
