### ISSUE TITLE
internal error in Guessit (for Medusa)

### ISSUE THREAD

**Issue by NicoLeOca** [guessit-io/guessit#348]
Synology last DSM

2016-10-12 15:47:39 ERROR    POSTPROCESSOR :: [47616b5] Exception generated in thread POSTPROCESSOR: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=2.1.1.dev0
string=None
options={'allowed_languages': set([u'ru', u'hu', u'en', u'nl', u'pt', u'de', u'jp', u'sv', u'it', u'fr', u'es', u'uk', u'ro', u'pl', u'he']), 'expected_group': set([u're:\\bF4ST3R\\b', u're:\\bTGNF4ST\\b', u're:\\bNovaRip\\b', u're:\\bNBY\\b', u're:\\bRiPRG\\b', u're:\\bbyEMP\\b', u're:\\b4EVERHD\\b', u're:\\bPOURMOi\\b', u're:\\bPARTiCLE\\b', u're:\\bTV2LAX9\\b', u're:\\bELITETORRENT\\b', u're:\\bRipPourBox\\b', u're:\\bF4ST\\b']), 'expected_title': ['re:(?

full logs:
https://gist.github.com/NicoLeOca/fff78977c8019b19b70ab72351d13137

@ratoaq2 FYI

**Comment by ratoaq2** [comment]
This is a  medusa issue, not really a guessit issue. It was a problem in one of our rules

**Comment by Toilal** [comment]
Yes, input string seems to be None.

**Comment by ratoaq2** [comment]
Not exactly the input string, but one of our rebulk rules 

https://github.com/pymedusa/Medusa/issues/1093#issuecomment-253190374

**Comment by NicoLeOca** [comment]
ok then
if you all know what's going on, I close this issue
