### ISSUE TITLE
Guessit takes 100% and never finish on some queries

### ISSUE THREAD

**Issue by 2ge** [guessit-io/guessit#353]
Try 

```
guessit frasier.s8e6-768660-tv3play.srt

$ guessit --version
+-------------------------------------------------------+
+                   GuessIt 2.1.0                       +
+-------------------------------------------------------+
+                   Rebulk 0.7.6                        +
+-------------------------------------------------------+
```

**Comment by SpootDev** [comment]
What does "768660" in the filename represent in this case?

**Comment by 2ge** [comment]
it represents some kind of ID I believe. Problem is not with output of wrong data, but guessit hangs, eats 100% cpu and never finish.

**Comment by Toilal** [comment]
Guessit thinks it's an episode range from 6 to 788660. So it performs an internal loop that can be long... It should no detect an episode range in this case.

**Comment by 2ge** [comment]
exactly; I can not control input, but it should not hang. 

Please implement some limit on episodes (series too...?), so it will not freeze. I think setting limit as 100 would be enough.

**Comment by Toilal** [comment]
I added a new feature in rebulk chain feature to add breaking condition when building those chain. So I set this condition to break the chain when difference with the previous value is greater than 100.

It requires rebulk > 0.8.0 that I just released.
