### ISSUE TITLE
Guessit is detecting the Daily Show as a movie

### ISSUE THREAD

**Issue by lenaxia** [guessit-io/guessit#355]
VideoSort is a plugin for NZBGet and uses Guessit to get metadata about incoming files. When I download the Daily Show it gets detected as a movie instead of as an episode.

`Executing post-process-script videosort\VideoSort.py for The.Daily.Show.2016.10.31.1080p.WEB.x264-HEAT`
`VideoSort: Forcing TV sorting (category: TV Shows)`
`VideoSort: filename: \\HOSHINO\Downloads\[Plex Temp Library]\TV Shows\The.Daily.Show.2016.10.31.1080p.WEB.x264-HEAT\the.daily.show.2016.10.31.1080p.web.x264-heat.mkv`
`VideoSort: Using NZB-Name`
`VideoSort: Guessing: The.Daily.Show.2016.10.31.1080p.WEB.x264-HEAT.mkv`
`VideoSort: 000000000000000000000000000000000000000000000 111`
`VideoSort: 000000000000000000000000000000000000000000000 000`
`VideoSort: 000000000000000000000000001111122222222222222 000`
`VideoSort: 00000000000000011112222222     00000111122222`
`VideoSort:                                01112    01111`
`VideoSort: ___________________.10.31._____.___.____-____.___`
`VideoSort: tttttttttttttttyyyy       sssss fff vvvv rrrr ccc`
`VideoSort: The.Daily.Show.2016.10.31.1080p.WEB.x264-HEAT.mkv`
`VideoSort: {u'type': u'movie'}`
`VideoSort: {u'title': u'The Daily Show'}`
`VideoSort: {u'year': 2016}`
`VideoSort: {u'screenSize': u'1080p'}`
`VideoSort: {u'format': u'WEB-DL'}`
`VideoSort: {u'videoCodec': u'h264'}`
`VideoSort: {u'releaseGroup': u'HEAT'}`
`VideoSort: {u'mimetype': u'video/x-matroska', u'container': u'mkv'}`
`VideoSort: {u'container': u'mkv'}`
`VideoSort: {`
`VideoSort:     [1.00] "mimetype": "video/x-matroska",`
`VideoSort:     [1.00] "unidentified": [`
`VideoSort:         "10 31"`
`VideoSort:     ],`
`VideoSort:     [1.00] "videoCodec": "h264",`
`VideoSort:     [1.00] "container": "mkv",`
`VideoSort:     [1.00] "format": "WEB-DL",`
`VideoSort:     [0.60] "title": "The Daily Show",`
`VideoSort:     [1.00] "releaseGroup": "HEAT",`
`VideoSort:     [1.00] "screenSize": "1080p",`
`VideoSort:     [1.00] "year": 2016,`
`VideoSort:     [1.00] "type": "movie"`
`VideoSort: }`
`VideoSort: Type: othertv`
`VideoSort: {`
`VideoSort:     [1.00] "mimetype": "video/x-matroska",`
`VideoSort:     [1.00] "unidentified": [`
`VideoSort:         "10 31"`
`VideoSort:     ],`
`VideoSort:     [1.00] "videoCodec": "h264",`
`VideoSort:     [1.00] "container": "mkv",`
`VideoSort:     [1.00] "format": "WEB-DL",`
`VideoSort:     [0.60] "title": "The Daily Show",`
`VideoSort:     [1.00] "releaseGroup": "HEAT",`
`VideoSort:     [1.00] "vtype": "othertv",`
`VideoSort:     [1.00] "screenSize": "1080p",`
`VideoSort:     [1.00] "year": 2016,`
`VideoSort:     [1.00] "type": "movie"`
`VideoSort: }`
`VideoSort: format: %t.%ext`
`VideoSort: path after subst: The Daily Show..mkv`
`VideoSort: path after cleanup: The Daily Show.mkv`
`VideoSort: destination path: \\HOSHINO\Downloads\[Plex Temp Library]/tv\The Daily Show.mkv`
`VideoSort: Moved: \\HOSHINO\Downloads\[Plex Temp Library]/tv\The Daily Show.mkv`
`VideoSort: Move satellites for \\HOSHINO\Downloads\[Plex Temp Library]\TV Shows\The.Daily.Show.2016.10.31.1080p.WEB.x264-HEAT\the.daily.show.2016.10.31.1080p.web.x264-heat.mkv`
`VideoSort: Cleanup`
`VideoSort: Deleted: \\HOSHINO\Downloads\[Plex Temp Library]\TV Shows\The.Daily.Show.2016.10.31.1080p.WEB.x264-HEAT\the.daily.show.2016.10.31.1080p.web.x264-heat.nfo`
`VideoSort: Deleted: \\HOSHINO\Downloads\[Plex Temp Library]\TV Shows\The.Daily.Show.2016.10.31.1080p.WEB.x264-HEAT\The.Daily.Show.2016.10.31.1080p.WEB.x264-HEAT.nzb`
`VideoSort: Deleted: \\HOSHINO\Downloads\[Plex Temp Library]\TV Shows\The.Daily.Show.2016.10.31.1080p.WEB.x264-HEAT\the.daily.show.2016.10.31.1080p.web.x264-heat.srr`
`VideoSort: Deleted: \\HOSHINO\Downloads\[Plex Temp Library]\TV Shows\The.Daily.Show.2016.10.31.1080p.WEB.x264-HEAT`
`Post-process-script videosort\VideoSort.py for The.Daily.Show.2016.10.31.1080p.WEB.x264-HEAT successful`

**Comment by Toilal** [comment]
For some reason, date is not guessed, leading to movie type...

```
For: The.Daily.Show.2016.10.31.1080p.WEB.x264-HEAT
GuessIt found: {
    "title": "The Daily Show", 
    "year": 2016, 
    "episode_title": "10 31", 
    "screen_size": "1080p", 
    "format": "WEB-DL", 
    "video_codec": "h264", 
    "release_group": "HEAT", 
    "type": "movie"
}
```

**Comment by ratoaq2** [comment]
this is the same issue of #351 and #362 is a proposal to fix it

**Comment by Toilal** [comment]
Merge of #362 fix this issue
