### ISSUE TITLE
Release group DHD is not properly detected

### ISSUE THREAD

**Issue by ratoaq2** [guessit-io/guessit#356]
Latest guessit development version:
```
commit 35e1ac640023aa20fb3efae72e0ea0ca270a1307
Author: Toilal <toilal.dev@gmail.com>
Date:   Wed Oct 12 00:05:12 2016 +0200

    Remove unused import
```

```
guessit -t episode "National.Geographic.Documentaries.S2016E15.720p.HDTV.x264.Mammoth.Back.from.the.Dead-DHD.mkv"
For: National.Geographic.Documentaries.S2016E15.720p.HDTV.x264.Mammoth.Back.from.the.Dead-DHD.mkv
GuessIt found: {
    "title": "National Geographic Documentaries", 
    "season": 2016, 
    "year": 2016, 
    "episode": 15, 
    "screen_size": "720p", 
    "format": "HDTV", 
    "video_codec": "h264", 
    "release_group": "Mammoth.Back.from.the.Dead-DHD", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
```

```
guessit -t episode "National.Geographic.Documentaries.S2016E17.720p.HDTV.x264.9.11.The.Longest.War-DHD"
For: National.Geographic.Documentaries.S2016E17.720p.HDTV.x264.9.11.The.Longest.War-DHD
GuessIt found: {
    "title": "National Geographic Documentaries", 
    "season": 2016, 
    "year": 2016, 
    "episode": 17, 
    "screen_size": "720p", 
    "format": "HDTV", 
    "video_codec": "h264", 
    "release_group": "9.11.The.Longest.War-DHD", 
    "type": "episode"
}
```

**Comment by Toilal** [comment]
I'm not sure I want to fix those cases. Episode title is at a really uncommon position ... Release group is supposed to be right after the `codec` (`x264`) or `format` (`HDTV`) match.

It works with most common ordering `National.Geographic.Documentaries.S2016E15.Mammoth.Back.from.the.Dead.720p.HDTV.x264-DHD.mkv` and  `National.Geographic.Documentaries.S2016E17.9.11.The.Longest.War.720p.HDTV.x264-DHD`

**Comment by ratoaq2** [comment]
I do agree with you. There are certain non sense cases that their fix doesn't bring any major benefit and still might require a lot of effort

**Comment by ratoaq2** [comment]
Just as additional info:

It seems that National Geographic follows that pattern: episode title after video codec:
```
guessit -t episode "National.Geographic.Documentaries.S2016E02.720p.HDTV.x264.Challenger.Disaster-Lost.Tapes-CURIOSITY"
For: National.Geographic.Documentaries.S2016E02.720p.HDTV.x264.Challenger.Disaster-Lost.Tapes-CURIOSITY
GuessIt found: {
    "title": "National Geographic Documentaries", 
    "season": 2016, 
    "year": 2016, 
    "episode": 2, 
    "screen_size": "720p", 
    "format": "HDTV", 
    "video_codec": "h264", 
    "release_group": "Challenger.Disaster-Lost.Tapes-CURIOSITY", 
    "type": "episode"
}
```

I've seen some scenarios like that

**Comment by Toilal** [comment]
Can't they name like other people ? :)

**Comment by duramato** [comment]
Just to add up another release as this "issue" is still present, and is not only reserved for DHD 
`National.Geographic.Documentaries.S2016E22.720p.HDTV.x264.hubbles.amazing.journey-plutonium`

**Comment by Toilal** [comment]
Really, I don't have any idea for a rule to implement this pattern ...

**Comment by ratoaq2** [comment]
There's a pattern for this issue and #196 ( `ulshd-the.right.stuff.1983.multi.1080p.bluray.x264.mkv`)

The release group is at the start or at the end separated by a dash and the rest is either `title` or `episode_title` separated by dots:
`ulshd-the.right.stuff.1983.multi.1080p.bluray.x264.mkv`: `release_group: ulshd`
`National.Geographic.Documentaries.S2016E22.720p.HDTV.x264.hubbles.amazing.journey-plutonium`: `release_group: plutonium`

`somegroup-super.title.2016.1080p.mkv`
`the.show.name.S01E02.720p.HDTV.x264.the.episode.title-othergroup`

The issue #196 is not so critical since the folder name often has all the information in a format that guessit already handles.

But for this one I can see more and more cases like that.
