### ISSUE TITLE
Enhance Season/Episode conflict solver

### ISSUE THREAD

**Issue by ratoaq2** [guessit-io/guessit#360]
For the latest development guessit version: `35e1ac640023aa20fb3efae72e0ea0ca270a1307`

Given:
`guessit "Coupling Season 1 - 4 Complete DVDRip/Coupling Season 4/Coupling - (4x03) - Bed Time.mkv"`

Then:
```
For: Coupling Season 1 - 4 Complete DVDRip/Coupling Season 4/Coupling - (4x03) - Bed Time.mkv
GuessIt found: {
    "title": "Coupling", 
    "season": [
        1, 
        2, 
        3, 
        4
    ], 
    "other": "Complete", 
    "format": "DVD", 
    "episode": 3, 
    "episode_title": "Bed Time",
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
```

The example above is a very good example that for `season` and `episode` the `__default__` conflict solver is not adequate.

The very first `filepart` (`Coupling Season 1 - 4 Complete DVDRip`) contains more matches*: `title`, `season`, `other` and `format`; but its `season` reflects the season range that the folder contains.
Only `season`, `other` and `format` are counted as matches during conflict solving logic, since `title` is added using an additional `Rule`.

Going to the right, the `filepart`s will always became more specific:
`Coupling Season 4` matches: `title` and `season` whereas the `season` is more specific. The `__default__` conflict solver for `season` just discards it because this `filepart` has less matches than the previous `filepart`, but in case of `season` and `episode`, it shouldn't. It should always give preference to the rightmost `filepart` when solving conflicts for these 2 fields.

And the last `filepart` contains `title`, `season`, `episode`, `episode_title`, `container`. Only `season`, `episode` and `container` are counted as matches during conflict solving logic.

In my humble opinion, the `conflict_solver` for `season` and `episode` should change to always give preference to the `rightmost` filepart, since that's the logic when organizing a video library: going to the right is always more specific; going to the left is always more generic.

**Comment by Toilal** [comment]
Feel free to enhance the default conflict solver using this idea. 

Only constraint is to make all unit tests pass, as usual, but I do agree with every word you wrote :)
