### ISSUE TITLE
Add project to OSS-Fuzz

### ISSUE THREAD

**Issue by OmgImAlexis** [guessit-io/guessit#368]
@Toilal not sure if you saw the announcement but Google is allowing open source projects like this to be added to their free fuzzer and I figured this may help find weird bugs that you weren't aware of.

https://alexgaynor.net/2016/dec/03/oss-fuzz-initial-impressions/
https://github.com/google/oss-fuzz

I know that they're mainly accepting C and C++ but there are wrappers for using LLVM with Python so I thought I'd open an issue anyway.

**Comment by Toilal** [comment]
It seems interesting, but I'm not sure i'll have time to go for it.
