### ISSUE TITLE
"3x3 Eyes" episodes wrong season/eps

### ISSUE THREAD

**Issue by SpootDev** [guessit-io/guessit#373]
File name: u'/mediakraken/mnt/zfsspoo/iscsi_share/HTPC_MediaBrowser/TV_Shows_Misc/3x3 Eyes (1991)/Season 2/3x3 Eyes - 2x01 - Descent.mkv'

Result: MatchesDict([('season', 3), ('episode', 3), ('episode_title', u'Eyes'), ('year', 1991), ('container', u'mkv'), ('type', u'episode')])

**Comment by Toilal** [comment]
For this particular case, maybe we should keep season and episode numbers that comes later in the file, but I'm not really sure ...

You can use `expected_title` option for this case, as a workaround.

```
$ guessit -T "3x3" "/mediakraken/mnt/zfsspoo/iscsi_share/HTPC_MediaBrowser/TV_Shows_Misc/3x3 Eyes (1991)/Season 2/3x3 Eyes - 2x01 - Descent.mkv"
For: /mediakraken/mnt/zfsspoo/iscsi_share/HTPC_MediaBrowser/TV_Shows_Misc/3x3 Eyes (1991)/Season 2/3x3 Eyes - 2x01 - Descent.mkv
GuessIt found: {
    "title": "3x3",
    "year": 1991,
    "season": 2,
    "episode_title": "Eyes",
    "episode": 1,
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

See #374 , I plan to add a configuration file for guessit for user to configure all possible hardcoded titles for those cases, as we can't handle all conflicting titles that will come in future.

**Comment by SpootDev** [comment]
Yeah, there will be so many "edge" cases like this a list might be the only realistic choice.

**Comment by Toilal** [comment]
Configuration file is now available.
