### ISSUE TITLE
Enhance expected_title and expected_group

### ISSUE THREAD

**Issue by ratoaq2** [guessit-io/guessit#376]
Series and movies names that contains numbers might confuse guessit.

```
guessit "The.100.Season.1.Complete"
For: The.100.Season.1.Complete
GuessIt found: {
    "title": "The", 
    "season": 1, 
    "episode": 0, 
    "other": "Complete", 
    "type": "episode"
}
```

An alternative is to use `expected_title` (same applies for `expected_group`), but it doesn't work as initially expected:
```
guessit -T "The 100" "The.100.Season.1.Complete"
For: The.100.Season.1.Complete
GuessIt found: {
    "title": "The", 
    "season": 1, 
    "episode": 0, 
    "other": "Complete", 
    "type": "episode"
}
```

An alternative is to use the exact string or regex, but the guessed title is not properly formatted.
```
guessit -T "re:The 100" "The.100.Season.1.Complete"
For: The.100.Season.1.Complete
GuessIt found: {
    "title": "The.100", 
    "season": 1, 
    "other": "Complete", 
    "type": "episode"
}
```
```
guessit -T "The_100" "The_100_Season_1_Complete"
For: The_100_Season_1_Complete
GuessIt found: {
    "title": "The_100", 
    "season": 1, 
    "other": "Complete", 
    "type": "episode"
}
```

My proposal is to enhance `expected_title` and `expected_group` for string matches.
The expected title/group input string could be used to generate a regex pattern to match the title/group and use the title/group itself as the match value:
`-T "The 100"` could generate a regex equivalent to `'re:(?<![\W_])The +100(?=[\W_]|$)'`, but the `match.value` is `The 100`
```
guessit -T "The 100" "The_100_Season_1_Complete"
For: The_100_Season_1_Complete
GuessIt found: {
    "title": "The 100", 
    "season": 1, 
    "other": "Complete", 
    "type": "episode"
}
```

I have an utility function that generates a regex pattern for a given expected title (it handles titles with `'` and `:` as well):
```
def prepare(string):
    """Prepare a string to be used as a regex in guessit expected_title.

    :param string:
    :type string: str
    :return:
    :rtype: str
    """
    # replace some special characters with space
    characters = {'-', '.', ',', '*', '(', ')'}
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)

    # replace unicode characters with period
    string = re.sub(r'[^\x00-\x7F]+', '.', string)

    # escape other characters that might be problematic
    string = re.escape(string)

    # dots (the replacement of unicode characters) shouldn't be escaped and should match 1 or more characters
    string = string.replace('\.', '.+')

    # ' should be optional
    string = string.replace(r"\'", r"'?")

    # spaces shouldn't be escaped
    string = string.replace('\ ', ' ')

    # replace multiple spaces with one
    string = re.sub(r'\s+', ' +', string.strip())

    # : should be optional or space
    string = string.replace(r"\:", r" ?")

    return r're:(?<![\W_]){name}(?=[\W_]|$)'.format(name=string)
```

IMO, this feature could simplify guessit configuration file for `expected_title` or `expected_group` as proposed in #374

**Comment by Toilal** [comment]
I agree with this idea, but the actual implementation seems complex.

I'll open a pull request.

**Comment by Toilal** [comment]
It should also be possible to give multiple input for `expected_title` and `expected_group` (as a first step before #374)

**Comment by ratoaq2** [comment]
The implementation is indeed complex. It was done when guessit was a blackbox and the only way to control expect titles from outside was using `re:...`
I'll check your implementation :+1:
