### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by OmgImAlexis** [guessit-io/guessit#391]
I'm not sure if this is a bug per se since it isn't actually valid.
Maybe assume the section between the title and screen_size is the season + episode?

```
➜  Medusa git:(develop) python tests/report_guessit.py "Supernatural.12E04.1080p.WEB-DL.DD5.1.H264-RARBG.mkv"
# guessit: 2.1.2.dev0  rebulk: 0.8.3.dev0
? Supernatural.12E04.1080p.WEB-DL.DD5.1.H264-RARBG.mkv
: title: Supernatural 12E04
  screen_size: 1080p
  format: WEB-DL
  audio_codec: AC3
  audio_channels: 5.1
  video_codec: h264
  release_group: RARBG
  container: mkv
  mimetype: video/x-matroska
  type: episode
  parsing_time: 0.147644996643
```

**Comment by Toilal** [comment]
Maybe we could add this as a pattern (ssEee) ... If it doesn't break any test case, it will be added.

**Comment by fernandog** [comment]
@rarbg is this a new format `ssEee` or a wrong name release? Can you please regex search your DB and see how many cases of this format exists? Otherwise no point to add this rule in guessit

**Comment by rarbg** [comment]
Its a typo guys
