### ISSUE TITLE
Not detecting alias

### ISSUE THREAD

**Issue by OmgImAlexis** [guessit-io/guessit#395]
I noticed with other shows if the dir has `name` and the file has `name (year)` the `name (year)` will be added as an alias but that's not happening for shows with names like so.

```
# guessit: 2.1.2.dev0  rebulk: 0.8.3.dev0
? /downloads/Shadowhunters.S02E01.720p.HDTV.x264-FLEET/Shadowhunters.The.Mortal.Instruments.S02E01.720p.HDTV.x264-FLEET.mkv
: season: 2
  episode: 1
  screen_size: 720p
  format: HDTV
  video_codec: h264
  video_encoder: x264
  release_group: FLEET
  title: Shadowhunters The Mortal Instruments
  container: mkv
  mimetype: video/x-matroska
  type: episode
  parsing_time: 0.190764904022
```

**Comment by ratoaq2** [comment]
This is not a guessit bug. The `report_guessit` tool in medusa is medusa specific with additional rules and properties that's present only in medusa, such as `alias`, `proper_tags` and `video_encoder`. These fields and rules don't exist in guessit. 

To report issues here you should use guessit command line or its API

**Comment by OmgImAlexis** [comment]
Ref: https://github.com/pymedusa/Medusa/issues/1889
