### ISSUE TITLE
Disk number not being detected

### ISSUE THREAD

**Issue by OmgImAlexis** [guessit-io/guessit#401]
For example season 7 comes in 6 disks so the files are like so.
Since S00E00 is detected as season + episode I would have expected this to be seen as season + disk number. This is mainly seen in older releases, for example this one is from 2011.

Greys.Anatomy.S07D1.NTSC.DVDR-ToF
Greys.Anatomy.S07D2.NTSC.DVDR-ToF
Greys.Anatomy.S07D3.NTSC.DVDR-ToF
Greys.Anatomy.S07D4.NTSC.DVDR-ToF
Greys.Anatomy.S07D5.NTSC.DVDR-ToF
Greys.Anatomy.S07D6.NTSC.DVDR-ToF

```
For: Greys.Anatomy.S07D6.NTSC.DVDR-ToF
GuessIt found: {
    "title": "Greys Anatomy", 
    "season": 7, 
    "episode_title": "D6", 
    "other": "NTSC", 
    "format": "DVD", 
    "release_group": "ToF", 
    "type": "episode"
}
```

**Comment by ratoaq2** [comment]
Fixed by #485
