### ISSUE TITLE
error while detect name

### ISSUE THREAD

**Issue by IDerr** [guessit-io/guessit#406]
===================== Guessit Exception Report =====================
version=2.1.1.dev0
string=[Zero-Raws].One.Piece.493-498.&.500-507.(CX.1280x720.VFR.x264.AAC)
options={'allowed_languages': set([u'ru', u'hu', u'en', u'nl', u'pt', u'de', u'jp', u'sv', u'it', u'fr', u'es', u'uk', u'ro', u'pl', u'he']), 'expected_group': set([u're:\\bF4ST3R\\b', u're:\\bTGNF4ST\\b', u're:\\bNovaRip\\b', u're:\\bNBY\\b', u're:\\bRiPRG\\b', u're:\\bbyEMP\\b', u're:\\bTV2LAX9\\b', u're:\\b4EVERHD\\b', u're:\\bRipPourBox\\b', u're:\\bPARTiCLE\\b', u're:\\bDHD\\b', u're:\\bELITETORRENT\\b', u're:\\bS4L\\b', u're:\\bF4ST\\b', u're:\\bPOURMOi\\b']), 'expected_title': ['re:(?= 0[^/\\\\])\\w+ it\\b', 're:(?<=[\\W_])3 +gatsu +no +Lion(?=[\\W_]|$)'], 'allowed_countries': set([u'gb', u'us']), 'episode_prefer_number': False, 'show_type': None, 'type': 'episode', 'implicit': True}

**Comment by ratoaq2** [comment]
This issue is not related to guessit. It was fixed in the correct repository
