### ISSUE TITLE
Wrong episode number + type

### ISSUE THREAD

**Issue by IDerr** [guessit-io/guessit#410]
For: [DefinitelyNotMe] Youjo Senki - 6.5 VOSTFR [1080p].mkv
GuessIt found: {
    "release_group": "DefinitelyNotMe",
    "title": "Youjo Senki",
    "alternative_title": "6 5",
    "subtitle_language": "French",
    "screen_size": "1080p",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "movie"
}

Should be 
{
    "release_group": "DefinitelyNotMe",
    "title": "Youjo Senki",
    "alternative_title": "**6.5**",
    "subtitle_language": "French",
    "screen_size": "1080p",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "**episode**"
}

Thanks a lot

**Comment by ratoaq2** [comment]
Why an episode doesn't have an episode number?

**Comment by IDerr** [comment]
My bad, instead of "alternative_title" it's should be "episode", but I don't know if a float value is correct or it's only integer...
