### ISSUE TITLE
wrong type + episode title

### ISSUE THREAD

**Issue by IDerr** [guessit-io/guessit#411]
For: [DeadFish] Little Witch Academia (2017) - 06v2 [720p][AAC].mp4
GuessIt found: {
    "release_group": "DeadFish",
    "title": "Little Witch Academia",
    "year": 2017,
    "episode_title": "06v2",
    "screen_size": "720p",
    "audio_codec": "AAC",
    "container": "mp4",
    "mimetype": "video/mp4",
    "type": "movie"
}

Should be 
{
    "release_group": "DeadFish",
    "title": "Little Witch Academia",
    "year": 2017,
    **"episode": "6"**,
    "screen_size": "720p",
    "audio_codec": "AAC",
    "container": "mp4",
    "mimetype": "video/mp4",
    "type": "**episode**"
}

Thanks a lot

**Comment by ratoaq2** [comment]
This is guessed just fine when using `-E` and `-t episode` options:

```
guessit -E -t episode "[DeadFish] Little Witch Academia (2017) - 06v2 [720p][AAC].mp4"
For: [DeadFish] Little Witch Academia (2017) - 06v2 [720p][AAC].mp4
GuessIt found: {
    "release_group": "DeadFish", 
    "title": "Little Witch Academia", 
    "year": 2017, 
    "episode": 6, 
    "version": 2, 
    "screen_size": "720p", 
    "audio_codec": "AAC", 
    "container": "mp4", 
    "mimetype": "video/mp4", 
    "type": "episode"
}
```

**Comment by IDerr** [comment]
Oh my bad, I never use flags :( 

Thanks a lot :D
