### ISSUE TITLE
Enhance anime detection: automatically use --prefer-episode-number

### ISSUE THREAD

**Issue by ratoaq2** [guessit-io/guessit#423]
Current guessit behavior:

```
For: [SomeGroup-Fansub]_Show_Name_727_[VOSTFR][HD_1280x720]
GuessIt found: {
    "release_group": "SomeGroup-Fansub", 
    "title": "Show Name", 
    "season": 7, 
    "episode": 27, 
    "subtitle_language": "French", 
    "other": "HD", 
    "screen_size": "720p", 
    "type": "episode"
}
```

It would be nice if guessit could auto-detect animes and switch to `--prefer-episode-number` automatically.

Anime release names have some patterns and conventions:
```
[SomeGroup-Fansub]_Show_Name_727_[VOSTFR][HD_1280x720]
[GROUP]Show_Name_726_[VOSTFR]_[V1]_[8bit]_[720p]_[2F7B3FA2]
Show Name 445 VOSTFR par Fansub-Resistance (1280*720) - version MQ
Anime Show Episode 159 v2 [VOSTFR][720p][AAC].mp4
[Group] Anime Super Episode 161 [VOSTFR][720p].mp4
Show.Name.-.476-479.(2007).[HorribleSubs][WEBRip]..[HD.720p]
Show Name - 722 [HD_1280x720].mp4
```

Hints that allow us to detect animes:
- `screen_size` inside a group: `[]` or `()`
- `release_group` inside a group and at the start of a filepart
- `version`, `crc32` and/or `video_profile` is/are present

In all these cases guessit should use absolute numbering instead of splitting season/episode. Probably an early rebulk rule could detect these patterns and provide the correct matches.

**Comment by ratoaq2** [comment]
It would be nice if `absolute_episode` (or something similar) could be added alongside `episode` to guessit output as well. So, other patterns such as `Show Name - 313-314 - s16e03-04` could be detected as well (but that's a separate topic)

**Comment by Toilal** [comment]
`absolute_episode` is one on the remaining item from https://github.com/guessit-io/guessit/issues/222, but I can't really find a smart algorithm for this property ...

**Comment by ratoaq2** [comment]
We have that covered here: https://github.com/pymedusa/Medusa/blob/master/tests/test_guessit.yml#L647-L692

We hooked some additional post processing rules to guessit to rectify standard guessit output. But those rules can't be reused in guessit because they are `workarounds` (some of them are really ugly and unmaintainable)

I managed to remove a lot of them from there with a proper implementation here in guessit.

**Comment by ratoaq2** [comment]
Brainstorm: one way to solve this one is to not disable the rules just because `-E` is not specified, but let them execute and then have a really earlier rule that can check if it's an anime or not based on those hints and based on that, remove/rename the matches.

**Comment by Toilal** [comment]
guessit 1.x had a second pass triggered in some edge cases, but I found better algorithms to avoid those second pass in guessit 2+.

But maybe we could bring back a second pass for those cases in guessit 2+ ...

**Comment by ratoaq2** [comment]
I don't know how was the implementation of guessit 1.x, but my first impression is that we should avoid a 2nd pass. But I can't say without actually evaluating it.
Not disabling some rules can also influence performance.

**Comment by Toilal** [comment]
I agree second pass is crap. I introduced it lately in guessit 1.x to fix some issues, and i'm happy it's still out from guessit 2 for now.

But for this particular issue, I can't find a reliable and early way to detect conditions you have stated without actually running a first pass.

> screen_size inside a group: [] or ()
release_group inside a group and at the start of a filepart
version, crc32 and/or video_profile is/are present

**Comment by ratoaq2** [comment]
After you execute all patterns (without disabling the absolute number patterns), you'll have all the matches (apart from the release group). At this point you can execute a rule to check if it seems to be an anime and prefer-number matches should be kept or discarded. 
Then the other existing rules will continue. 

In theory, it could work, but I didn't get a chance to try it
