### ISSUE TITLE
Bad Match with Country

### ISSUE THREAD

**Issue by jlebard** [guessit-io/guessit#425]
Hi, 

Conventional writing for a tv show likely that : 
Title.Country.SX.EX ....
http://v2.api.guessit.io/?filename=This.Is.Us.S01.E08.720p.WEBRip.X264-TEAM

the country is writed like that : US, UK, ... but with with tv show finish with us likely : This.Is.Us => this return title => This is (US) and not This is us. 
for exemple : 
http://v2.api.guessit.io/?filename=This.Is.Us.US.S01.E08.720p.WEBRip.X264-TEAM 
should be return title : This is us (US) ...
can you modify for country match with 2 capital letters and not just 2 letters ?

Thx, and sorry for my bad English

**Comment by jlebard** [comment]
https://github.com/guessit-io/guessit/issues/358
Sorry double ...

**Comment by ratoaq2** [comment]
Closing this as duplicate
