### ISSUE TITLE
Ignoring "--type movie"

### ISSUE THREAD

**Issue by BamBalaam** [guessit-io/guessit#429]
I am using guessit as a python module, trying to match while using command line options.

I give the function the option "--type movie" but for some reason the output has both "season/episode" and "type: movie" on its dictionary.

    raw_film_title = '007.Spectre.[HDTC.MD].[TRUEFRENCH]'

    guessit(raw_film_title, "--type movie") 

    MatchesDict([('season', 0), ('episode', 7), ('title', u'Spectre'), ('format', u'HDTC'), ('other', u'MD'), ('language', <Language [fr]>), ('type', u'movie')])

**Comment by ratoaq2** [comment]
You could  use :

`guessit(raw_film_title, options={'type': 'movie'})`

But still. It's detecting season and episode. 
Which  guessit version are you using?

**Comment by BamBalaam** [comment]
I am using the version that was installed by pip: 2.1.1

**Comment by BamBalaam** [comment]
Here's another notable example:

    >>> from guessit import guessit
    >>> title = "10 Cloverfield Lane.[Blu-Ray 1080p].[MULTI]"
    >>> guessed_title = guessit(title, options={'type': 'movie'})
    >>> guessed_title
    MatchesDict([('episode', 10), ('title', 'Cloverfield Lane'), ('format', 'BluRay'), 
    ('screen_size', '1080p'), ('language', <Language [mul]>), ('type', 'movie')])
    >>>
