### ISSUE TITLE
UnicodeEncodeError with non english filename

### ISSUE THREAD

**Issue by Crupuk** [guessit-io/guessit#43]
Here is a exemple :

touch /tmp/15x15\ Les\ Simpson\ -\ Boire\ et\ déboires.avi
guessit /tmp/15x15\ Les\ Simpson\ -\ Boire\ et\ déboires.avi
```
Traceback (most recent call last):
  File "/usr/bin/guessit", line 9, in <module>
    load_entry_point('guessit==0.6', 'console_scripts', 'guessit')()
  File "/usr/lib/python2.6/site-packages/guessit/__main__.py", line 109, in main
    info = options.info.split(','))
  File "/usr/lib/python2.6/site-packages/guessit/__main__.py", line 32, in detect_filename
    print('For:', filename)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 63: ordinal not in range(128)
```

```
python --version
Python 2.6.6
```

I don't know how to resolv it :-( 

Thanks

**Comment by Crupuk** [comment]
I don't know why, but after upgrading subliminal the bug come back...

**Comment by Toilal** [comment]
Could you try to manually remove this line : https://github.com/guessit-io/guessit/blob/1.x/guessit/__main__.py#L214 ?

**Comment by Toilal** [comment]
@Crupuk ? Have you tried my previous message ?

**Comment by Crupuk** [comment]
@Toilal No, sorry, and i can't reproduce the bug right now... :-( I don't undestand what append
