### ISSUE TITLE
Problems with obfuscated/scrambled tags and title

### ISSUE THREAD

**Issue by pannal** [guessit-io/guessit#433]
-T is ignored and title is the release-group + obfuscated:

```
guessit "Season 06/e01.1080p.bluray.x264-wavey-obfuscated.mkv" -T "The Office (US)"
For: Season 06/e01.1080p.bluray.x264-wavey-obfuscated.mkv
GuessIt found: {
    "season": 6,
    "episode": 1,
    "screen_size": "1080p",
    "format": "BluRay",
    "video_codec": "h264",
    "title": "wavey-obfuscated",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

-T is ignored again:

```
guessit "e01.1080p.bluray.x264-wavey-obfuscated.mkv" -T "The Office (US)"
For: e01.1080p.bluray.x264-wavey-obfuscated.mkv
GuessIt found: {
    "episode": 1,
    "screen_size": "1080p",
    "format": "BluRay",
    "video_codec": "h264",
    "title": "wavey-obfuscated",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

and again:

```
guessit "The.office.S06e01.1080p.bluray.x264-wavey-obfuscated.mkv" -T "The Office (US)"
For: The.office.S06e01.1080p.bluray.x264-wavey-obfuscated.mkv
GuessIt found: {
    "title": "The office",
    "season": 6,
    "episode": 1,
    "screen_size": "1080p",
    "format": "BluRay",
    "video_codec": "h264",
    "release_group": "wavey-obfuscated",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

**Comment by ratoaq2** [comment]
This is not how the parameter -T works. It searches for the match in the string and none of the strings above contains "The Office US" in it

You can specify a list of expected titles and only if the string contains one of the expected titles you'll get a title match.

**Comment by pannal** [comment]
Ah, OK. Didn't realize that. 

Wouldn't it be viable to do some kind of levensthein comparison of the two strings and act accordingly in addition to a simple substring match?

**Comment by fernandog** [comment]
@ratoaq2 can't guessit add the `obfuscated` and `scrambled` in `other` property? This words are quite common in nzb releases/indexers

**Comment by ratoaq2** [comment]
@fernandog can you provide some examples of release names with "scrambled" in their name?

**Comment by fernandog** [comment]
_Hells.Kitchen.US.S17E08.1080p.HEVC.x265-MeGusta-Obfuscated/c48db7d2aeb040e8a920a9fd6effcbf4.mkv

Blue.Bloods.S08E09.1080p.HEVC.x265-MeGusta-Obfuscated/afaae96ae7a140e0981ced2a79221751.mkv

MacGyver.2016.S02E09.CD-ROM.and.Hoagie.Foil.1080p.AMZN.WEBRip.DDP5.1.x264-NTb-Scrambled/c329b27187d44a94b4a25b21502db552.mkv

The.Late.Late.Show.with.James.Corden.2017.11.27.Armie.Hammer.Juno.Temple.Charlie.Puth.1080p.AMZN.WEB-DL.DDP2.0.H.264-monkee-Scrambled/42e7e8a48eb7454aaebebcf49705ce41.mkv

@duramato any other we should consider?

**Comment by fernandog** [comment]
BTW never saw this: CD-ROM

**Comment by duramato** [comment]
`Educating Greater Manchester S01E07 720p HDTV x264-PLUTONiUM-AsRequested`
`Im A Celebrity Get Me Out Of Here S17E14 HDTV x264-PLUTONiUM-xpost`
, to name a few.

But for example `Enigma S01E123 720p HDTV x264-Sweet-Star`'s group is `Sweet-Star`

**Comment by fernandog** [comment]
Don't we need to tell guessit the name of mkv too?

**Comment by ratoaq2** [comment]
I don't see `Scrambled` or `Obfuscated` in @duramato 's  examples

**Comment by duramato** [comment]
That's becouse I gave examples of other words that are the "same" as `Scrambled` or `Obfuscated`.

**Comment by fernandog** [comment]
But the video file for those are a bunch of number/letters like in my examples?

**Comment by duramato** [comment]
yes

**Comment by fernandog** [comment]
@ratoaq2 I can confirm `postbot`, `xpost` and `AsRequested`  also uses scrambled files

I also found this other scenario:
`Stranger.Things.S02E05.Chapter.Five.Dig.Dug.720p.NF.WEBRip.DD5.1.x264-PSYPHER-AsRequested-Obfuscated `

**Comment by ratoaq2** [comment]
What does "xpost, postbot, asrequested" mean?
Re-post? Done as requested and/or by a bot?

**Comment by duramato** [comment]
Yes think so, they tags added by a Usenet indexer. odfuscated and scrambled are tags added by another indexer.
