### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by pschupp01** [guessit-io/guessit#466]
Hello,

I was wondering if your online service were down.
We keep getting a "502 Bad Gateway" error on http://guessit.io

Thanks.

**Comment by Toilal** [comment]
If you want to test the rest API, it's https://api.guessit.io/. @wackou owns the root domain, I don't know what's running on it.

**Comment by wackou** [comment]
sorry, web server went out of memory, this is now fixed (it's only a redirect to the doc on ReadTheDocs anyway).
