### ISSUE TITLE
Tricky tvshow to detect

### ISSUE THREAD

**Issue by usenetDude** [guessit-io/guessit#494]
Hey there,

there is a very strange result for the releases of 19-2.
They are named:
`19-2.2014.S03E01.GERMAN.720p.HDTV.x264-ACED`
and contain the show [19-2 (2014)](https://www.themoviedb.org/tv/61546-19-2).

Guessit detects the first part as a date and gets
`MatchesDict([
('date', datetime.date(2014, 2, 19)),
('season', 3), ('episode', 1),
 ('language', <Language [de]>), 
('screen_size', '720p'), ('format', 'HDTV'),
('video_codec', 'h264'), ('title', 'ACED'),
('type', 'episode')])`

Any chance to fix this? Is 19-2.2014 even a "real" dateformat anywhere? Is it possible for a legit show to start with a date?

**Comment by labrys** [comment]
Yes the show 11/22/63 about JFK getting shot for example.

**Comment by ratoaq2** [comment]
Is it ok for you to specify expected titles? 

`guessit -T "19-2"  19-2.2014.S03E01.GERMAN.720p.HDTV.x264-ACED`

You can specify as many expected titles as you want. Usually titles which include numbers might lead to wrong results in certain corner cases or specific scenarios

**Comment by ratoaq2** [comment]
I'm labelling `Won't fix` since all series or movies that are just numbers can't be properly detected without using `-T` option (`expected-title`)

You can have all these cases stored in a guessit config file:
```
  -c CONFIG, --config CONFIG
                        Filepath to the configuration file. Configuration
                        contains the same options as those command line
                        options, but option names have "-" characters replaced
                        with "_". If not defined, guessit tries to read a
                        configuration default configuration file at
                        ~/.guessit/options.(json|yml|yaml) and
                        ~/.config/guessit/options.(json|yml|yaml). Set to
                        "false" to disable default configuration file loading.
```

And an example of configuration:

```json
~/.guessit/options.json

{
  "expected_title": [
    "OSS 117",
    "19-2",
    "11.22.63"
  ]
}
```
