### ISSUE TITLE
VC1 implementation

### ISSUE THREAD

**Issue by Diabolino** [guessit-io/guessit#502]
it"s possible add VC-1 codec https://fr.wikipedia.org/wiki/VC-1

actually il recognized as country
`country: {
value: "SAINT VINCENT AND THE GRENADINES",
raw: "VC",
start: 51,
end: 53
},`

**Comment by ratoaq2** [comment]
It's already implemented in a separate branch and PR:
https://github.com/guessit-io/guessit/pull/476/files#diff-d9ae695c8119e58c2ec435b6deae2d53R97

**Comment by ratoaq2** [comment]
Fixed in develop
