### ISSUE TITLE
Expired SSL Certificate on api.guessit.io

### ISSUE THREAD

**Issue by pschupp01** [guessit-io/guessit#504]
The SSL certificate is expired, causing issue with using your api inside the browser.
(cf https://api.guessit.io )

**Comment by pschupp01** [comment]
@wackou From what I understood, you own that domain.
Any news about this?

**Comment by wackou** [comment]
thanks for pinging me, this indeed fell through the cracks. I have started the process of renewing the certificate and will coordinate with @Toilal to update the site ASAP. Sorry for the inconvenience.

**Comment by Toilal** [comment]
I just upgraded all services and updated certificates, all is ok now. API is running latest release. Sorry about the downtime, I could not handle this before.

**Comment by pschupp01** [comment]
Hey,
@wackou @Toilal 
I'm pinging on this issue, as the certificate is invalid again on https://api.guessit.io
