### ISSUE TITLE
Follow ISO standards for language recognition, and exclude them for any other option

### ISSUE THREAD

**Issue by Nottt** [guessit-io/guessit#505]
Like many others, I use radarr/sonarr and they can rename the files to include the language in the filename but guessit doesn't seem to be following a standard, and sometimes even think a language code is part of a release group. 

Any reason why [ISO-639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) [ISO-639-2](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes) are not followed ? 

You seem to only understand some codes like ENG/RU and not others or [CHINESE] [PORTUGUESE] and okay I think you can keep doing that, but please follow the ISO codes too so every tool and needs get satisfied.

Also to fix it being tagged as a release group I suggest excluding them as allowed in other tags, unless they are around words, so you can have filenames like [pt] or .por. or [PT+ENG] or [PT/ENG] or (por) and still never get it wrong. 

This would fix #500 and avoid issues like #462 in the future. Please :(

Examples : 

```
For: Test (2013) [WEBDL-1080p] [x264 AC3] [ENG+RU+PT] [NTb].mkv
GuessIt found: {
    "title": "Test",
    "year": 2013,
    "format": "WEB-DL",
    "screen_size": "1080p",
    "video_codec": "h264",
    "audio_codec": "AC3",
    "language": [
        "English",
        "Russian"
    ],
    "release_group": "PT] [NTb]",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "movie"
}
```

But ENG+RU works :

```
For: Test (2013) [WEBDL-1080p] [x264 AC3] [ENG+RU] [NTb].mkv
GuessIt found: {
    "title": "Test",
    "year": 2013,
    "format": "WEB-DL",
    "screen_size": "1080p",
    "video_codec": "h264",
    "audio_codec": "AC3",
    "language": [
        "English",
        "Russian"
    ],
    "release_group": "NTb",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "movie"
}
```
So clearly the standard are not being fully followed, and can also leak to other tags even if only followed by symbols or empty space ( we can safely assume they are not a dictionary word )

Please please :(

**Comment by Toilal** [comment]
We already use ISO, but using all countries and languages from ISO causes far too many false positive. There are options to override the default list of recognized countries and languages though.

**Comment by Nottt** [comment]
How can you get false positive if you only consider then if they around
symbols?

How much words exists with + / () or []? None.

If you do this, it's impossible to have false positives while also making
possible to use the languages. And it seems hypocrite to support some but
not others.

Also I do not have control over guessit in my situation, I'm only a end
user of a application that uses guessit to download subtitles.

**Comment by ratoaq2** [comment]
Unfortunately is not that simple.
You can easily find false positives:
`This is it` would detect: "`country: Iceland, language: Italian`"
or
`Super movie pt 2` would detect `language: portuguese`
or
`Nada por aquí (2013)` would detect `language: portuguese`

There's a list of blacklisted words: 
https://github.com/guessit-io/guessit/blob/89a01b012403a4dab5bc928b47878bd4a085e3a5/guessit/rules/common/words.py#L74

We're planning to make guessit advanced options configurable (countries and languages first - https://github.com/guessit-io/guessit/pull/476 ) and probably even the common words list.

**Comment by ratoaq2** [comment]
And around symbols issues:
`Youth.In.Revolt.(Be.Bad).2009.MULTI.1080p.LAME3*92-MEDIOZZ`
would detect: `country: Belarus`

**Comment by Toilal** [comment]
For now, it's up to the end user application maintainer to build a configurable list of allowed languages/countries that could be given to guessit when parsing filenames.

**Comment by Nottt** [comment]
None of your examples has them together with symbols.

This is it (IT) = Should dectect Italian language and movie this is it.

At least add language recognition if it's between symbols.

**Comment by ratoaq2** [comment]
@Toilal, pt and por are in the common words, therefore blacklisted. The user can't control that. And that's why it's not detected

**Comment by Toilal** [comment]
Ho I see ... Even if allowed languages/countries options are defined ?

**Comment by ratoaq2** [comment]
Yes... Even with that defined. Probably when fixing #476 guessit will not detect all languages by default anymore and this blacklist probably shouldn't take place when detecting language and countries. But need to see if there will be any implication (glad that we have so many test scenarios)

**Comment by Nottt** [comment]
@ratoaq2 @Toilal can you at least fix this?

"release_group": "PT+DE] [STANDARD]",

Just that is enough, I care more about not messing up the release group tag than to really identify the language. Please?

**Comment by pannal** [comment]
Yeah I consider this a "my issue" (as Sub-Zero integrates guessit). I'll implement the expected languages functionality.

**Comment by ratoaq2** [comment]
#512 only improved but didn't fixed the issue
