### ISSUE TITLE
H264-20-40 is wrongly parsed as episodes 20-40

### ISSUE THREAD

**Issue by p0psicles** [guessit-io/guessit#507]
When parsing the following release title, it's interpreting the `-20-40` as episodes 20 to 40.
While actually this is a season pack.

I believe the -20-40 stands for the quality encoding profile. And for me personally it can be ignored.

Title:
`The.Good.Wife.Season.6.480p.HDTV.H264-20-40.WEB-DL`

Guessit log:
```
guessit "The.Good.Wife.Season.6.480p.HDTV.H264-20-40.WEB-DL                                                                            L"
For: The.Good.Wife.Season.6.480p.HDTV.H264-20-40.WEB-DL
GuessIt found: {
    "title": "The Good Wife",
    "season": 6,
    "screen_size": "480p",
    "format": [
        "HDTV",
        "WEB-DL"
    ],
    "video_codec": "h264",
    "episode": [
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40
    ],
    "type": "episode"
}
```

**Comment by fernandog** [comment]
ping @duramato

**Comment by duramato** [comment]
`-20-40` is the group

**Comment by fernandog** [comment]
@duramato group should be in the end right? 

In this example is next to the source and the codec: .H264-20-40.WEB-DL

**Comment by p0psicles** [comment]
Sometime it has the `.Webdl` at the end and sometime it doesn't. But as this seems to be a convention where all the tags are separated by a dot, I assume the `H264-20-40` is one tag.

**Comment by p0psicles** [comment]
Hmm now I'm also starting to doubt. It could be a group. But also then I could live with it if it's ignored.

**Comment by fernandog** [comment]
If is a group then its in the wrong place.

Anyway guessit should dectect it as EPISODES when between codec and source

**Comment by Toilal** [comment]
Please keep in mind that guessit should guess NON scene release name. 

So this result is expected, and you should consider adding "20-40" in expected group configuration option.

```
-G EXPECTED_GROUP, --expected-group EXPECTED_GROUP
                        Expected release group (can be used multiple times)
```

BTW, this group name just suck :) (maybe one day, a group with take WEBDL for it's name, it will be fun)

**Comment by p0psicles** [comment]
I think that's something we can do. @fernandog @ratoaq2 what do you think?

**Comment by ratoaq2** [comment]
Yes, we can add expected_group. Guessit can't detect that as a group since the release name ends with WEB-DL instead of 20-40

**Comment by ratoaq2** [comment]
Closing this as using `expected_group` is the suggested solution
