### ISSUE TITLE
Handling plurals in titles

### ISSUE THREAD

**Issue by laryan61** [guessit-io/guessit#508]
Just discovered Guessit. And with my first trial run I discovered it doesn't handle Movie titles with plurals. Where the file name is "The Devils Backbone (2001).avi" and it the title returned should be "The Devil's Backbone (2001)". Maybe this is by design? Could be returned as an alternate title.

I have a script that feeds the proper movie title and year into OMDB's api to return details about the movie. Using your script would save me from using my cobbled up code to guess the title.

**Comment by ratoaq2** [comment]
That's outside guessit scope. Guessit only detects patterns and output their values. It doesn't have intelligence to understand english

**Comment by laryan61** [comment]
I've written and (continuously modify) a script that does guess the movie name from the text string. Currently I'm using a dictionary of word pair replacements like; "devils:devil's" as well as pairs like "&;and" and "II:2", etc. to help it find the correct movie title.

It script (is mostly) working. But I was hoping to toss a chunk of my code and insert guessit.
