### ISSUE TITLE
Request: Parsing the IMDB number

### ISSUE THREAD

**Issue by laryan61** [guessit-io/guessit#509]
I think this would be a nice addition to your program.

**Comment by ratoaq2** [comment]
Could you provide a real example of release name with imdb number?

**Comment by laryan61** [comment]
To clarify. It would be nice if guessit would return the IMDB number in its results. I realize the user would most likely require a OMDB account to accomplish this. But wouldn't think that would be a big deal. Have the user add their OMDB account information in a configuration file. If its not there, then don't query for the IMBD number.

**Comment by Toilal** [comment]
If you mean performing an API call against IMDB to retrieve some info, then guessit won't handle this. It's a filename parser, nothing more.

**Comment by ratoaq2** [comment]
Closing this one since it's outside guessit scope.
Other tools could use guessit filename parser together with online databases to do this.
