### ISSUE TITLE
avchd group is not detected because it's in front of the show's name

### ISSUE THREAD

**Issue by vBm** [guessit-io/guessit#530]
There were already fixes for this type of detection but it seems no one reported `avchd` yet.
We can see info about wrongful detection in #196 and a fix for `blow` and `ulshd` groups in https://github.com/guessit-io/guessit/commit/fea26f3d67698b31899fdffa43626c899df5d33a

So please add `avchd` to the list of those somewhat silly groups that put their name first.

Example is `avchd-modern.family.s02e01.720p.bluray.x264.mkv`
Using guessit from develop branch and 3afb850be95698a46f1c878be408ddf7f671b408 commit.
```
e:\toolz\repository\guessit (develop -> origin)
λ guessit "avchd-modern.family.s02e01.720p.bluray.x264.mkv"
For: avchd-modern.family.s02e01.720p.bluray.x264.mkv
GuessIt found: {
    "video_codec": "H.264",
    "title": "modern family",
    "season": 2,
    "episode": 1,
    "screen_size": "720p",
    "source": "Blu-ray",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

**Comment by ratoaq2** [comment]
I don't get why release groups choose file formats for their name.

`AVCHD (Advanced Video Coding High Definition)`

**Comment by vBm** [comment]
Mockery, who knows?
Oldest their release i saw was:
`Equilibrium.2002.1080p.BluRay.x264-AVCHD (Uploaded 8y 11M 17d 1h 27m 36s ago on 2009-Feb-24) - (86.00 MB/8157F)`

**Comment by ratoaq2** [comment]
For now, I'm flagging this one as Won't Fix.
I'll leave it open with a low priority.

**Comment by vBm** [comment]
Out of curiosity, why `Won't Fix` ?
It's a legit group name that exist for quite some time.

**Comment by ratoaq2** [comment]
Because it's really hard to fix it without breaking other scenarios. And you can still use `--expected-group` parameter:

```
guessit -G avchd "avchd-modern.family.s02e01.720p.bluray.x264.mkv"
For: avchd-modern.family.s02e01.720p.bluray.x264.mkv
GuessIt found: {
    "release_group": "avchd", 
    "title": "modern family", 
    "season": 2, 
    "episode": 1, 
    "screen_size": "720p", 
    "source": "Blu-ray", 
    "video_codec": "H.264", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
```

I'm also happy to accept PRs that would fix this issue.

**Comment by Toilal** [comment]
With current develop version, it just give the expected result, and please don't tell us AVCHD is a legit group name, this name is just dumb.

```
? avchd-modern.family.s02e01.720p.bluray.x264.mkv
: video_codec: H.264
  video_profile: Advanced Video Codec High Definition
  title: modern family
  season: 2
  episode: 1
  screen_size: 720p
  source: Blu-ray
  container: mkv
  mimetype: video/x-matroska
  type: episode
```
