### ISSUE TITLE
SRT subtitles from addic7ed for show "Troy: Fall of a City" is not being parsed correctly

### ISSUE THREAD

**Issue by marcelpaulo** [guessit-io/guessit#531]
I was trying to rename these subtitles downloaded from addic7ed, using the info parsed by guessit:

`Troy - Fall of a City - 01x01 - Black Blood.-MTB(SD, 720p).English.C.orig.Addic7ed.com.srt`

and here's the result:

```
paulo@monk:~/watch$ guessit -j Troy\ -\ Fall\ of\ a\ City\ -\ 01x01\ -\ Black\ Blood.-MTB\(SD\,\ 720p\).English.C.orig.Addic7ed.com.srt 
{"title": "Troy", "alternative_title": "Fall of a City", "season": 1, "episode": 1, "episode_title": "Black Blood -MTB", "screen_size": "720p", "subtitle_language": "English", "release_group": "C.orig.Addic7ed.com", "container": "srt", "mimetype": "text/plain", "type": "episode"}
```

The correct name of the show is: **Troy: Fall of a City**.

Even if I try to parse it feeding it the expected title, it doesn't parse it correctly:

```
paulo@monk:~/watch$ guessit -j -T 'Troy: Fall of a City' Troy\ -\ Fall\ of\ a\ City\ -\ 01x01\ -\ Black\ Blood.-MTB\(SD\,\ 720p\).English.C.orig.Addic7ed.com.srt 
{"title": "Troy", "alternative_title": "Fall of a City", "season": 1, "episode": 1, "episode_title": "Black Blood -MTB", "screen_size": "720p", "subtitle_language": "English", "release_group": "C.orig.Addic7ed.com", "container": "srt", "mimetype": "text/plain", "type": "episode"}
```

My version of guessit, cloned from develop 3afb850, running on Xubuntu 17.10:

```
paulo@monk:~/watch$ guessit --version
+-------------------------------------------------------+
+                   GuessIt 3.0.0.dev0                  +
+-------------------------------------------------------+
+                   Rebulk 0.9.0                        +
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|     https://github.com/guessit-io/guessit/issues.     |
+-------------------------------------------------------+
```

**Comment by ratoaq2** [comment]
This is completely expected.

All the titles with a `-` or `:` separator will be parsed into `title` plus `alternative_title`. You could use both information in your rename script.

And the `expected_title` is intended to only search the input string for the given expected title, and `Troy: Fall of a City` is not in the input string `Troy - Fall of a City - 01x01 - Black Blood.-MTB(SD, 720p).English.C.orig.Addic7ed.com.srt`.
But `Troy - Fall of a City` is:

```
guessit T "Troy - Fall of a City" -y "Troy - Fall of a City - 01x01 - Black Blood.-MTB(SD, 720p).English.C.orig.Addic7ed.com.srt"
? Troy - Fall of a City - 01x01 - Black Blood.-MTB(SD, 720p).English.C.orig.Addic7ed.com.srt
: title: Troy - Fall of a City
  season: 1
  episode: 1
  episode_title: Black Blood -MTB
  screen_size: 720p
  subtitle_language: en
  release_group: C.orig.Addic7ed.com
  container: srt
  mimetype: text/plain
  type: episode
```

**Comment by marcelpaulo** [comment]
Thanks for the explanation, @ratoaq2 !

I guess then there's no proper solution to my srt rename script when the show name is improperly encoded in the filename, you see, I extract the show name from the srt file using guessit, and then loop over all video files, extracting their show names with guessit and comparing each one with the srt show name.
