### ISSUE TITLE
Incorrect Title Detection

### ISSUE THREAD

**Issue by darthShadow** [guessit-io/guessit#537]
Version:
```
guessit --version

+-------------------------------------------------------+
+                   GuessIt 3.0.0.dev0                  +
+-------------------------------------------------------+
+                   Rebulk 0.9.0                        +
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|     https://github.com/guessit-io/guessit/issues.     |
+-------------------------------------------------------+
```

Console Output:
```
guessit "[Chyuu] Nanatsu no Taizai - Imashime no Fukkatsu - 10 [720p][8BC6417A].mkv"

For: [Chyuu] Nanatsu no Taizai - Imashime no Fukkatsu - 10 [720p][8BC6417A].mkv
GuessIt found: {
    "release_group": "Chyuu",
    "title": "Nanatsu no Taizai",
    "episode_title": "Imashime no Fukkatsu",
    "episode": 10,
    "screen_size": "720p",
    "crc32": "8BC6417A",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```
The episode title should be returned as an alternative title, if I am not wrong. This is actually Season 2, Episode 10 as per [TheXem.de](http://thexem.de/xem/show/4207).

I know this may be a long shot but, given the fixes for line detection, I hope that this too can be fixed. Any options that could be passed to help it guess correctly?

**Comment by Toilal** [comment]
Well, I don't see how we can guess it's season 2 from this filename only ... Really.

**Comment by darthShadow** [comment]
Problem is not with the season detection, it's with the title detection. If the title had been parsed correctly to be `Nanatsu no Taizai - Imashime no Fukkatsu` instead of just `Nanatsu no Taizai`, it would have been handled properly since there is a mapping present in the XEM database mapping that title to season 2.

**Comment by ratoaq2** [comment]
Guessit is just a release name parser. From the name it will parse with title and alternate title. It's up to the caller to use these two information to match the correct show and the correct season

**Comment by ratoaq2** [comment]
Closing it as that's the expected behavior. Feel free to reopen if you think it should be handled differently
