### ISSUE TITLE
[Feature Request] Support `pathlib.Path` for Python >=3.4

### ISSUE THREAD

**Issue by labrys** [guessit-io/guessit#542]
Using a `pathlib.Path` with guessit results in `AttributeError: '*Path' object has no attribute 'find'`.  A work-around in the meantime is to typecast the `pathlib.Path` to str before passing it to guessit.  It would be nice to add support for `pathlib.Path` so it can be passed directly.

**Comment by Toilal** [comment]
Available in 3.0.0
