### ISSUE TITLE
Incorrect title/season when filename contains "Series" and year

### ISSUE THREAD

**Issue by hpsbranco** [guessit-io/guessit#550]
guessit 'From.Dusk.Till.Dawn.The.Series.2014.S01E10.720p.BluRay.DD5.1.x264-DON.mkv' -t episode

For: From.Dusk.Till.Dawn.The.Series.2014.S01E10.720p.BluRay.DD5.1.x264-DON.mkv
GuessIt found: {
    "title": "From Dusk Till Dawn The",
    "season": [
        2014,
        1
    ],
... correct stuff
}

If we remove the year or the word "Series" from the filename, everything is fine.

**Comment by Toilal** [comment]
It won't be easy to fix, because some test cases and matching patterns relies on `Serie(s)` keyword.

**Comment by Toilal** [comment]
Series has been removed from default configuration.
