### ISSUE TITLE
Country/Language broken in python

### ISSUE THREAD

**Issue by dremy7** [guessit-io/guessit#553]
```
+-------------------------------------------------------+
+                   GuessIt 3.0.0                       +
+-------------------------------------------------------+
+                   Rebulk 0.9.0                        +
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|     https://github.com/guessit-io/guessit/issues.     |
+-------------------------------------------------------+

$ guessit "Show.UK.S01E01.720p.HDTV.x264-FAKE.mkv"
For: Show.UK.S01E01.720p.HDTV.x264-FAKE.mkv
GuessIt found: {
    "title": "Show", 
    "country": "UNITED KINGDOM", 
    "season": 1, 
    "episode": 1, 
    "screen_size": "720p", 
    "source": "HDTV", 
    "video_codec": "H.264", 
    "release_group": "FAKE", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}

$ python3
>>> from guessit import guessit
>>> guessit("Show.UK.S01E01.720p.HDTV.x264-FAKE.mkv")
MatchesDict([('title', 'Show UK'), ('season', 1), ('episode', 1), ('screen_size', '720p'), ('source', 'HDTV'), ('video_codec', 'H.264'), ('release_group', 'FAKE'), ('container', 'mkv'), ('mimetype', 'video/x-matroska'), ('type', 'episode')])
```
In the above example, command line gives the country properly parsed out of the file but when using python the country code is included in the title with no country field given in the results.
Something similar happens with languages:
```
$ guessit "Show.UK.S01E01.SPANISH.720p.HDTV.x264-FAKE.mkv"
For: Show.UK.S01E01.SPANISH.720p.HDTV.x264-FAKE.mkv
GuessIt found: {
    "title": "Show", 
    "country": "UNITED KINGDOM", 
    "season": 1, 
    "episode": 1, 
    "language": "Spanish", 
    "screen_size": "720p", 
    "source": "HDTV", 
    "video_codec": "H.264", 
    "release_group": "FAKE", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
$ python3
>>> guessit("Show.UK.S01E01.SPANISH.720p.HDTV.x264-FAKE.mkv")
MatchesDict([('title', 'Show UK'), ('season', 1), ('episode', 1), ('episode_title', 'SPANISH'), ('screen_size', '720p'), ('source', 'HDTV'), ('video_codec', 'H.264'), ('release_group', 'FAKE'), ('container', 'mkv'), ('mimetype', 'video/x-matroska'), ('type', 'episode')])
```
Again via command line the language is properly guessed but in python it thinks the language is the episode title. 

I have been unable to get guessit to generate a result that contains a country or language in python no matter where I put the country/language in the file name.

Examples above are with python 3.5

**Comment by guessit-dev** [comment]
I ran into the same and noticed you need to specify allowed countries/languages `guessit("Show.UK.S01E01.SPANISH.720p.HDTV.x264-FAKE.mkv", {'allowed_languages': ['es']})` and `guessit("Show.UK.S01E01.720p.HDTV.x264-FAKE.mkv", {'allowed_countries': ['gb']})` should do it.

**Comment by dremy7** [comment]
What if you want all languages to be allowed? I'm using this in a script where I want it to be able to detect if it's a foreign language video or not and the input file could potentially be in any language.

**Comment by JohnDoee** [comment]
The default options are probably different when using the commandline command. My results are actually worse than yours for some reason.

If you want to see the options that the commandline tool uses, try adding

    print(options)

to this line https://github.com/guessit-io/guessit/blob/develop/guessit/__main__.py#L41

The easy fix is probably just to copy those options, I guess.
