### ISSUE TITLE
Movie not recognized correctly

### ISSUE THREAD

**Issue by xamandre** [guessit-io/guessit#558]
With 2.1.4
GuessIt found: {
    "title": "The Dark Knight",
    "year": 2008,
    "format": "BluRay",
    "screen_size": "1080p",
    "release_group": "CtrlHD",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "movie"
}

with 3.0
GuessIt found: {
    "episode_details": "Final",
    "title": "The Dark Knight",
    "year": 2008,
    "source": "Blu-ray",
    "screen_size": "1080p",
    "release_group": "CtrlHD",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}

of course subliminal cannot recognize the correct subtitles.
The movie name is 
The Dark Knight (2008) [Bluray-1080p-CtrlHD]

**Comment by VeNoMouS** [comment]
Define the `type` as `movie`

```
>>> from guessit import guessit
>>> guessit('The Dark Knight (2008) [Bluray-1080p-CtrlHD]', {'type': 'movie'})
MatchesDict([('title', 'The Dark Knight'), ('year', 2008), ('source', 'Blu-ray'), ('screen_size', '1080p'), ('release_group', 'CtrlHD'), ('type', 'movie')])
>>> 
```

**Comment by alashow** [comment]
I think that's the job of `guessit`. If I wanted to guess it my self, why would I use `guessit`?

What do authors think about this?

It looks like it fails when there is a string after year part.

**Comment by VeNoMouS** [comment]
@Toilal whats your thoughts.

**Comment by Toilal** [comment]
Those two cases should be guessed properly as a movie. I'll try to spend some time to fix some issues in the next few days.

**Comment by Toilal** [comment]
> with 3.0
> GuessIt found: {
> "episode_details": "Final",
> "title": "The Dark Knight",
> "year": 2008,
> "source": "Blu-ray",
> "screen_size": "1080p",
> "release_group": "CtrlHD",
> "container": "mkv",
> "mimetype": "video/x-matroska",
> "type": "episode"
> }

No problem here :

For: The Dark Knight (2008) [Bluray-1080p-CtrlHD]
GuessIt found: {
    "title": "The Dark Knight",
    "year": 2008,
    "source": "Blu-ray",
    "screen_size": "1080p",
    "release_group": "CtrlHD",
    "type": "movie"
}

**Comment by alashow** [comment]
```
For: Movie 2018 Digital Extras.mkv
GuessIt found: {
    "title": "Movie",
    "year": 2018,
    "episode_title": "Digital Extras",
    "episode_details": "Extras",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}```

Version: 3.0.0

**Comment by Toilal** [comment]
Understood for this part of the issue @alashow. Problem is that `Extras` and `Bonus` keywords triggers an "episode_details" property that makes guessit switch an `episode` type. I'll remove those values as they are often found in movies too ...
