### ISSUE TITLE
Expected titles not working as expected when using as a python module

### ISSUE THREAD

**Issue by getpanoramic** [guessit-io/guessit#592]
>guessit("20-20 2018.04.16 James Comey [720p].ts", options=dict(expected_titles=["20-20"]))
`
MatchesDict([('episode', 20), ('date', datetime.date(2018, 4, 16)), ('title', 'James Comey'), ('screen_size', '720p'), ('container', 'ts'), ('mimetype', 'video/vnd.dlna.mpeg-tts'), ('type', 'episode')])
`
vs 

>guessit "20-20 2018.04.16 James Comey [720p].ts" -T "20-20"
```
For: 20-20 2018.04.16 James Comey [720p].ts
GuessIt found: {
    "title": "20-20",
    "date": "2018-04-16",
    "episode_title": "James Comey",
    "screen_size": "720p",
    "container": "ts",
    "mimetype": "video/vnd.dlna.mpeg-tts",
    "type": "episode"
}
```

**Comment by medariox** [comment]
It's `expected_title`.

**Comment by getpanoramic** [comment]
Doh! My bad
Thanks!
