### ISSUE TITLE
Wrong quality when parsing Bluray files

### ISSUE THREAD

**Issue by IDerr** [guessit-io/guessit#601]
Describe the bug
Parsing BD as SD-DVD instead of BluRay

To Reproduce
Instead of BluRay, use BD to reproduce

Parsed [NeatBluRay] Hibike! Euphonium S02E09 VOSTFR (BD 1920x1080 8bits FLAC) into release_group: NeatBluRay, title: Hibike! Euphonium, season: 2, episode: [9], subtitle_language: fr, source: BDRip, screen_size: 1080p, aspect_ratio: 1.778, color_depth: 8-bit, audio_codec: FLAC, type: episode, parsing_time: 0.0323510169983, total_time: 0.0324549674988, absolute_episode: [], quality: SD DVD

Expected behavior
The parser should resolve the quality as BluRay instead of SD

Latest dev commit

Thanks a lot for your work !

**Comment by VeNoMouS** [comment]
Update guessit?

```
>>> import guessit
>>> guessit.__version__
'3.0.4'
>>> pprint(guessit.guessit('[NatBluRay] Hibike! Euphonium S02E09 VOSTFR (BD 1920x1080 8bits FLAC)').items())
[('release_group', 'NatBluRay'),
 ('title', 'Hibike! Euphonium'),
 ('season', 2),
 ('episode', 9),
 ('subtitle_language', <Language [fr]>),
 ('source', 'Blu-ray'),
 ('screen_size', '1080p'),
 ('aspect_ratio', 1.778),
 ('color_depth', '8-bit'),
 ('audio_codec', 'FLAC'),
 ('type', 'episode')]
>>>
```

picks up as source blu-ray for me...

**Comment by IDerr** [comment]
@VeNoMouS thanks, I was using a version used by another project, but the latest version gives me the same result as yours.
VOSTFR means Orginal voice subtitle french, it's normal for this part. 

Thanks :D

**Comment by VeNoMouS** [comment]
Ah was not aware of the term "VOSTFR" , thanks for the heads up :)
