### ISSUE TITLE
[Python module] MatchesDict inconsistencies with multiple filenames

### ISSUE THREAD

**Issue by Nowasky** [guessit-io/guessit#611]
GuessIt 3.0.4

Running from command line: (working as expected):
python -m guessit -t movie --expected-title "Avengers Infinity War" "Avengers Infinity War 2018 1080p WEB-DL H264 AC3-EVO" "Avengers Infinity War 2018 HEVC 1080p BluRay DTS x265-LEGi0N" "Avengers-Infinity War 2018 BRRip 1080p DD5 1 H265-d3g"
For: Avengers Infinity War 2018 1080p WEB-DL H264 AC3-EVO
GuessIt found: {
    "title": "Avengers Infinity War",
    "year": 2018,
    "screen_size": "1080p",
    "source": "Web",
    "video_codec": "H.264",
    "audio_codec": "Dolby Digital",
    "release_group": "EVO",
    "type": "movie"
}
For: Avengers Infinity War 2018 HEVC 1080p BluRay DTS x265-LEGi0N
GuessIt found: {
    "title": "Avengers Infinity War",
    "year": 2018,
    "video_codec": "H.265",
    "video_profile": "High Efficiency Video Coding",
    "screen_size": "1080p",
    "source": "Blu-ray",
    "audio_codec": "DTS",
    "release_group": "LEGi0N",
    "type": "movie"
}
For: Avengers-Infinity War 2018 BRRip 1080p DD5 1 H265-d3g
GuessIt found: {
    "title": "Avengers Infinity War",
    "year": 2018,
    "source": "Blu-ray",
    "other": [
        "Reencoded",
        "Rip"
    ],
    "screen_size": "1080p",
    "audio_codec": "Dolby Digital",
    "audio_channels": "5.1",
    "video_codec": "H.265",
    "release_group": "d3g",
    "type": "movie"
}

Running as python module:
>>> from guessit import guessit
>>> guessit('Avengers Infinity War 2018 1080p WEB-DL H264 AC3-EVO''Avengers Infinity War 2018 HEVC 1080p BluRay DTS x265-LEGi0N "Avengers-Infinity War 2018 BRRip 1080p DD5 1 H265-d3g"', options={'expected_title': ['Avengers Infinity War'], 'type': 'movie'})
MatchesDict([('title', 'Avengers Infinity War'), ('alternative_title', '2018'), ('screen_size', '1080p'), ('source', ['Web', 'Blu-ray']), ('video_codec', ['H.264', 'H.265']), ('audio_codec', ['Dolby Digital', 'DTS']), ('year', 2018), ('video_profile', 'High Efficiency Video Coding'), ('other', ['Reencoded', 'Rip']), ('audio_channels', '5.1'), ('release_group', 'd3g"'), ('type', 'movie')])

**Comment by ratoaq2** [comment]
You're passing multiple filenames as one string in the API, that's the issue

**Comment by Nowasky** [comment]
Thanks! So what's the right way to do It?

**Comment by Nowasky** [comment]
Sorry, I built the string in a wrong way when performing the test.

Here's the properly quoted string in the command:

 guessit("Avengers Infinity War 2018 1080p WEB-DL H264 AC3-EVO" "Avengers Infinity War 2018 HEVC 1080p BluRay DTS x265-LEGi0N" "Avengers-Infinity War 2018 BRRip 1080p DD5 1 H265-d3g", options={'expected_title': ['Avengers Infinity War'], 'type': 'movie'})
MatchesDict([('title', 'Avengers Infinity War'), ('alternative_title', '2018'), ('screen_size', '1080p'), ('source', ['Web', 'Blu-ray']), ('video_codec', ['H.264', 'H.265']), ('audio_codec', ['Dolby Digital', 'DTS']), ('year', 2018), ('video_profile', 'High Efficiency Video Coding'), ('other', ['Reencoded', 'Rip']), ('audio_channels', '5.1'), ('release_group', 'd3g'), ('type', 'movie')])

OR

guessit("'Avengers Infinity War 2018 1080p WEB-DL H264 AC3-EVO' 'Avengers Infinity War 2018 HEVC 1080p BluRay DTS x265-LEGi0N' 'Avengers-Infinity War 2018 BRRip 1080p DD5 1 H265-d3g'", options={'expected_title': ['Avengers Infinity War'], 'type': 'movie'})
MatchesDict([('title', "'Avengers Infinity War 2018"), ('screen_size', '1080p'), ('source', ['Web', 'Blu-ray']), ('video_codec', ['H.264', 'H.265']), ('audio_codec', ['Dolby Digital', 'DTS']), ('year', 2018), ('video_profile', 'High Efficiency Video Coding'), ('other', ['Reencoded', 'Rip']), ('audio_channels', '5.1'), ('release_group', "d3g'"), ('type', 'movie')])

**Comment by ratoaq2** [comment]
You need to call guessit for each input string

**Comment by Nowasky** [comment]
Okay, thanks!
