### ISSUE TITLE
Medusa guessit not detecting series

### ISSUE THREAD

**Issue by rrd911** [guessit-io/guessit#612]
Medusa Info: | Branch: master Commit: Unknown Version: 0.3.4 Database: 44.14
-- | --
Python Version: | 2.7.15 (default, Jan 24 2019, 16:32:39) [GCC 8.2.0]
SSL Version: | OpenSSL 1.1.1b 26 Feb 2019
OS: | Linux-4.15.0-54-generic-x86_64-with

Using Medusa the files with [somename] at the begining are not being detected. If I remove the [somename] Medusa detects the file and processes the file. The brackets seems to confuse the file detections.

WARNING  POSTPROCESSOR :: [] /anime/[Golumpa] Black Clover - 91 [FuniDub 720p x264 AAC] [F5FB6110].mkv: Processing failed: Not enough information to determine what episode this is

**Comment by Toilal** [comment]
Everything seems ok from guessit API

http://api.guessit.io/?filename=/anime/[Golumpa]%20Black%20Clover%20-%2091%20[FuniDub%20720p%20x264%20AAC]%20[F5FB6110].mkv
