### ISSUE TITLE
Title parsed incorrectly if it contains the sequence 'Vita'

### ISSUE THREAD

**Issue by marcelpaulo** [guessit-io/guessit#613]
If the movie title contains the character **&**, it's parsed incorrectly. I stumbled across this with this movie: *Vita.&.Virginia.2018.720p.H.264.YTS.LT.mp4*:

```
paulo:~/tmp$ guessit Vita.\&.Virginia.2018.720p.H.264.YTS.LT.mp4
For: Vita.&.Virginia.2018.720p.H.264.YTS.LT.mp4
GuessIt found: {
    "subtitle_language": "Italian",
    "other": "PS Vita",
    "title": "& Virginia",
    "year": 2018,
    "screen_size": "720p",
    "video_codec": "H.264",
    "release_group": "YTS.LT",
    "container": "mp4",
    "mimetype": "video/mp4",
    "type": "movie"
}
```

I'm running latest develop (950ca79) on Xubuntu 18.04.03.

**Comment by Toilal** [comment]
Issue is not caused by `&`, but because Vita is guessed as `PS Vita`. I'm not sure what we should do here.

**Comment by marcelpaulo** [comment]
Oh, you're right:

```
paulo:~/tmp$ touch 'Foo.&.Bar.2018.720p.H.264.YTS.LT.mp4'
paulo:~/tmp$ guessit Foo.\&.Bar.2018.720p.H.264.YTS.LT.mp4
For: Foo.&.Bar.2018.720p.H.264.YTS.LT.mp4
GuessIt found: {
    "title": "Foo & Bar",
    "year": 2018,
    "screen_size": "720p",
    "video_codec": "H.264",
    "release_group": "YTS.LT",
    "container": "mp4",
    "mimetype": "video/mp4",
    "type": "movie"
}
```

I'll change the issue title to reflect this.

**Comment by medariox** [comment]
@Toilal 
I would make the regex more restrictive by requiring the `PS` instead of making it optional. See: https://github.com/guessit-io/guessit/blob/74dbb0c7420cee18969926aba9cc06b8959daa0e/guessit/rules/properties/other.py#L84

**Comment by Toilal** [comment]
Well, in fact it then guess `vita` as Italian `subtitle_language`.

There's a `v` prefix in default configuration (`options.json`) for subtitles, but it doesn't make much sense to me and can conflict with too many common words. 

So i'll remove this possible subtitle prefix from the default configuration, and add `vfr` as French langage synonym as it impact a single test case.

**Comment by medariox** [comment]
Thanks for the fix! Just FYI, `vfr` actually doesn't have anything to do with the French language. It is the acronym for `Variable Frame Rate`, which often appears in anime releases.

**Comment by Toilal** [comment]
Oh thanks! I'll just add this value to `other` property then.
