### ISSUE TITLE
doubts on how to handle 'SnnEmm - episode title.EXT'

### ISSUE THREAD

**Issue by sandrotosi** [guessit-io/guessit#619]
hello, let's take this example:

```
In [496]: guessit.guessit('S04E01 - title of the episode.mp4')
Out[496]: 
MatchesDict([('season', 4),
             ('episode', 1),
             ('title', 'title of the episode'),
             ('container', 'mp4'),
             ('mimetype', 'video/mp4'),
             ('type', 'episode')])
```

there are several situation where the filename doesnt contain the series title before the SnnEmm tag, but currently `guessit` uses the title of the episode (that usually follows SnnEmm) as the series title

should `guessit` try, instead, not to switch title and episode?

**Comment by labrys** [comment]
If you have files like this they are usually contained in a folder named after the series.  Pass the series folder as part of the name and it will detect it too.

**Comment by Toilal** [comment]
Thanks for reporting this issue, but I really don't see what we could do better here. I do agree with  @labrys comment too.

You may also apply a post treatment on guessit results, with some TVDB API queries ...

**Comment by sandrotosi** [comment]
well, hold on a second: are you suggesting i should pass the full path to guessit and not only the filename?

**Comment by Toilal** [comment]
That's it, it can help if the folder name match the Serie name.

https://api.guessit.io/?filename=/Some.Serie/S04E01.some.episode.mkv

```
{ 
   "title":"Some Serie",
   "season":4,
   "episode":1,
   "episode_title":"some episode",
   "container":"mkv",
   "mimetype":"video/x-matroska",
   "type":"episode"
}
```

**Comment by sandrotosi** [comment]
that's very interesting, as i've also tried https://api.guessit.io/?filename=/very/long/path/as/part/of/an/automation/Some.Serie/S04E01.some.episode.mkv (which is my workflow) and it detects it correctly -- i'm gonna switch to full path then, thanks!
