### ISSUE TITLE
proper_count raw does not output full match

### ISSUE THREAD

**Issue by RaggyDoo** [guessit-io/guessit#626]
When running the following steps I would expect guessit to output the full match which it seems to do when the count is only 1, however when the count is 2 it still only outputs 1. eg.

**Actual:**

> In [72]: t = guessit.guessit('The.Big.Bang.Theory.S01E01.Funny.Title.REPACK.PROPER.1080p.WEB-DL.DDP5.1.H.264-NOGRP', '-a')
> In [73]: t['proper_count'].raw
> Out[73]: 'PROPER'
> 
> In [74]: t = guessit.guessit('The.Big.Bang.Theory.S01E01.Funny.Title.REPACK.1080p.WEB-DL.DDP5.1.H.264-NOGRP', '-a')
> In [75]: t['proper_count'].raw
> Out[75]: 'REPACK'

**Expected?**

> In [72]: t = guessit.guessit('The.Big.Bang.Theory.S01E01.Funny.Title.REPACK.PROPER.1080p.WEB-DL.DDP5.1.H.264-NOGRP', '-a')
> In [73]: t['proper_count'].raw
> Out[73]: 'REPACK.PROPER'

Is this by design, or is there anything I can do better here?

**Comment by Toilal** [comment]
I'm not sure if it's a bug (solvable) or by design (but still weird). I'll be happy to fix this one.
