### ISSUE TITLE
crew in front of filename not recognized

### ISSUE THREAD

**Issue by snickers2k** [guessit-io/guessit#629]
```
guessit muhhd-arcticdogs2019-webrip-1080p.mkv

For: muhhd-arcticdogs2019-webrip-1080p.mkv
GuessIt found: {
    "title": "muhhd-arcticdogs2019",
    "source": "Web",
    "other": "Rip",
    "screen_size": "1080p",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "movie"
}

```

this is happening for a lot of filenames lately.
as of this, there is no further lookup possible.

would be really thankful if you could fix this. thanks

**Comment by Toilal** [comment]
It's not possible, sorry, at least not with the way guessit works.

**Comment by snickers2k** [comment]
> It's not possible, sorry, at least not with the way guessit works.

Wouldn't it be possible if guessit is taking known release_groups into consideration?

https://github.com/filebot/data/blob/master/release-groups.txt
