### ISSUE TITLE
known release_groups

### ISSUE THREAD

**Issue by snickers2k** [guessit-io/guessit#632]
Sorry, i dont know if you read closed issues.

So im still curious if it is possible to take a list of known relase_groups for mathing against them.

https://github.com/filebot/data/blob/master/release-groups.txt

this can fix the wrong/not matching in front of filenames

**Comment by Toilal** [comment]
Currently, guessit is a pure parser an try to not rely on any hardcoded list like this one.

I think of something that could help fix invalid guesses based on some community driven data like this one, but it's still in my head at the moment. For now, I prefer to close those kind of issues, but that's a good idea and maybe guessit 4.x will be smarter thanks to community driven feedback and data.
