### ISSUE TITLE
Help config option.Json

### ISSUE THREAD

**Issue by Sirfrancis17** [guessit-io/guessit#635]
Hi
I would like to modify the options file. 
I want to add a Micro category in the screen size 
I want movies with m1080 in the name, guessit performer it as "Micro" 
"progressive": [
        "360",
        "480",
        "540",
        "576",
        "900",
        "1080",
        "368",
        "720",
        "1440",
        "2160",
        "4320",
        "Micro": "m1080"
      ]
I've tried that line but it makes me wrong

I have a other problem 
When the chapter has multiple chapters in the name the format is as follows:
Grandpa 1x01-02
The output of guessit is "[1, 2]"
How can I change the format to E1E2 No brackets 
Any help? 
Thank you

**Comment by Sirfrancis17** [comment]
Any help? Any tutorial with option.json file?

**Comment by Toilal** [comment]
Sorry. You may post-process the output by writing a python script. Alors, the option.json file has to keep the same structure, it seems you try to introduce a key/value inside a list of value.
