### ISSUE TITLE
guessit.io domain name ownership

### ISSUE THREAD

**Issue by wackou** [guessit-io/guessit#643]
I haven't been active in guessit in a long time now, but I am still the owner of the guessit.io domain name. I'd like to relinquish it to someone that is more active on the project, and closer to a maintainer. @Toilal I guess that would be you, can we look into doing that transfer?

**Comment by Toilal** [comment]
I agree, what's the process now ? You may need my email adress, toilal.dev@gmail.com.

**Comment by wackou** [comment]
well, that depends on what domain name registrar you plan to use. Usually, the process is started from the receiving side, which then sends a request to the current owner to accept the transfer. So the first step for you is to choose which registrar you want to use, then initiate a transfer request. Then I'll accept the transfer requests, and (roughly) that should be it.
I am currently using gandi.net as the registrar, but you can use any one you want.

**Comment by Toilal** [comment]
@wackou `.io` tld is a bit expensive, I think the domain name could just be abandonned as it's only used to redirect to readthedocs and for the testing API.

**Comment by OmgImAlexis** [comment]
I’d be happy to chip in $50 USD to cover the domain.

**Comment by wackou** [comment]
either way, it's up to you. Currently, the domain is registered until February next year, at which time it'll expire if it hasn't been transferred before. Just let me know

**Comment by Toilal** [comment]
Thanks @OmgImAlexis really glad you wish to help. I need to think about how people could donate though. Maybe with Github Sponsors ?

**Comment by wackou** [comment]
just a ping to let you know that the domain expires on Feb 24, 2021, so if you want to keep it we're going to have to transfer it before that.

**Comment by OmgImAlexis** [comment]
@Toilal if it comes down to it I'm happy to PayPal you the money so it doesn't expire.

**Comment by Toilal** [comment]
@OmgImAlexis I'm very pleased if you can help. I plan to transfer and renew the domain name before it's expired during January.

You can send some bucks here: https://paypal.me/toilal

**Comment by OmgImAlexis** [comment]
How much did you need in euros?

**Comment by Toilal** [comment]
I think I'll buy it up on Gandi, seems to be 38.40€ per year for io domains.

**Comment by OmgImAlexis** [comment]
> I think I'll buy it up on Gandi, seems to be 38.40€ per year for io domains.

Done.

**Comment by Toilal** [comment]
Bonjour @wackou,

J'ai commencé la procédure, je me suis créé un compte sur gandi.net et maintenant j'ai besoin d'un code d'autorisation pour le transfert que tu dois me fournir. Peux tu me l'envoyer par mail ? Merci

**Comment by Toilal** [comment]
Thank you for the gift @OmgImAlexis, I'll renew the domain thanks to you :+1:

**Comment by wackou** [comment]
@Toilal : you got mail! :)
@OmgImAlexis : thanks for the donation to keep the domain name!
