### ISSUE TITLE
get json output while using module

### ISSUE THREAD

**Issue by 0-MegaMind-0** [guessit-io/guessit#644]
I'm relatively new to python like running `guessit filename --json`

how could i get son results instead of `MatchesDict`
when running from python 
```
>>> from guessit import guessit
>>> guessit('Treme.1x03.Right.Place,.Wrong.Time.HDTV.XviD-NoTV.avi')  
```
couldn't find api docs

**Comment by 0-MegaMind-0** [comment]
`json.dumps(guessit("test.E01.200403.720p-group.mp4"))`

gives a `TypeError: Object of type date is not JSON serializable`
error as there is date in title 
and shows up like this in dict `('date', datetime.date(2003, 4, 20))`

**Comment by 0-MegaMind-0** [comment]
for now i'm using 
```
import datetime
from guessit import guessit
import json

def default(o):
    if isinstance(o, (datetime.date, datetime.datetime)):
        return o.isoformat()

file = "test.E01.200403.720p-group.mp4""
print(json.dumps(guessit(file),  default=default))
```

but would like to know if there is a better way to handle this

**Comment by pawamoy** [comment]
You are close, check the code, there's a JSON encoder for the guessit result. Look in `__main__.py`, you'll see how it's used.

**Comment by 0-MegaMind-0** [comment]
ah thanks i was trying to figure a way to use it something like 
`guessit(file, options={"output":"json"}` and thought program might have a way to handle it
Thanks for the solution :)
