### ISSUE TITLE
Exception in Bazarr

### ISSUE THREAD

**Issue by charlesdab** [guessit-io/guessit#655]
Hi All!

Let me know what information I should add to this.

I'm using Bazarr for media server subtitle management (https://github.com/morpheus65535/bazarr) which relies on GuessIt! Unfortunately I've found that every time I run Bazarr it fails due to an exception with GuessIt.

This PasteBin includes a log from Bazarr with a sample failure: https://pastebin.com/tdbpfZs2

Hardware: Synology NAS
OS: Linux-3.10.105-x86_64-with
Deployment: Bazarr Docker Container

Is there any more information I can provide? Thanks!

**Comment by charlesdab** [comment]
Sorry, I am new to Git so I didn't know to check closed issues. It looks like the same issue as here:
https://github.com/guessit-io/guessit/issues/645

But morpheus has since updated GuessIt to 3.1.1

**Comment by Toilal** [comment]
Thanks, please reopen if it still occurs in 3.1.1

**Comment by morpheus65535** [comment]
@Toilal last comment state that the issue si still present with 3.1.1. Why not investigate instead of closing it?

**Comment by Toilal** [comment]
Pastebin doesn't work, it seems there's more info in #645

**Comment by Toilal** [comment]
Seems to be the same as #647 too

**Comment by charlesdab** [comment]
@Toilal @morpheus65535 Sorry, the pastbin was set to expire. I think this one may have the same log files:

https://pastebin.com/jM2VhxxX

**Comment by Toilal** [comment]
I have tested a bunch of errors in this pastebin and seems to work properly in current version.
