### ISSUE TITLE
ValueError: unused keyword argument 'private_parent'

### ISSUE THREAD

**Issue by idan2402** [guessit-io/guessit#656]
Hey there! I'm trying to use a service called Subliminal. It worked fine on my system until a few weeks ago when it started just saying "1 error" on every download.
When I ran it in debug mode it says "ValueError: unused keyword argument 'private_parent'" and "Please report at https://github.com/guessit-io/guessit/issues." (screenshot provided).
Tried reinstalling through pip and it didn't work.

I use Python 3.6.8 and Subliminal 2.1.0 on Windows 10 Enterprise LTSC.

Thank you in advance :)

![image](https://user-images.githubusercontent.com/31790575/91163364-21a3e380-e6d6-11ea-903f-7f150b42b38c.png)

**Comment by Toilal** [comment]
Please try to remove regex module pour tour python installation.

**Comment by hyiltiz** [comment]
`regex` module is a dependency for a lot of other packages though. Removing it is not even a feasible workaround.

**Comment by Toilal** [comment]
I think there's also an environment variable to disable regex module import from guessit, check sources.

**Comment by hyiltiz** [comment]
Recursive string search in the project for `os.getenv` or `getenv` showed nothing.

**Comment by Toilal** [comment]
It's in rebulk : https://github.com/Toilal/rebulk/blob/master/rebulk/remodule.py

**Comment by Toilal** [comment]
With current version, rebulk has to be explicitly enabled with `REBULK_REGEX_ENABLED`, so this issue should not occur.
