### ISSUE TITLE
Empty string returns type: 'movie'

### ISSUE THREAD

**Issue by LaundroMat** [guessit-io/guessit#662]
I just stumbled on this:

```
>>> from guessit import guessit
>>> guessit('')
MatchesDict([('type', 'movie')])

```

Is this expected? I'm using `guessit = "^3.1.1"`

**Comment by Toilal** [comment]
I understand it seems to be unexpected, but basically guessit consider any input as a movie by default, so this occurs. 

It only change type to serie afterwards, when some other guessed properties seems to be more related to series than movies (season, episode, ...).

So it won't get fixed, you can check for empty input before invoking guessit.
