### ISSUE TITLE
Detect Open Matte when given as "Open Matte"

### ISSUE THREAD

**Issue by plotski** [guessit-io/guessit#689]
Example: "Foo Bar 2015 Open Matte 1080p WEB-DL DD+5.1 H.264"

Current master interprets "Open Matte" as `alternative_title`.

This should be easy to fix in `options.json`, but only in the develop branch and I'm not supposed to make PRs from that.

**Comment by Toilal** [comment]
`develop` branch is the default branch, you can and should make PRs from that, no problem. Anyway, i'll fix it, thanks for reporting.
