### ISSUE TITLE
1883.s01e05.1080p.web.h264-cakes.mkv  title not guessed properly

### ISSUE THREAD

**Issue by razsteinmetz** [guessit-io/guessit#723]
does not guess the title correctly, but rather make 1883 the absolute episode.

**Comment by komeiji-ak1ra** [comment]
Use `-T EXPECTED_TITLE, --expected-title EXPECTED_TITLE` option please.

```
$ guessit -T 1883 1883.s01e05.1080p.web.h264-cakes.mkv
For: 1883.s01e05.1080p.web.h264-cakes.mkv
GuessIt found: {
    "title": "1883",
    "season": 1,
    "episode": 5,
    "screen_size": "1080p",
    "source": "Web",
    "video_codec": "H.264",
    "release_group": "cakes",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

**Comment by razsteinmetz** [comment]
Yes, of course, but I want to guess the title, I don't know its the expected one (out of many files)

**Comment by Toilal** [comment]
For guessit, it's more likely an absolute episode number than a title. There's no bug here.

Then guessit could enhanced to consider that SxxExx is stronger, and discard weak episode patterns like this one as a consequence, for the real title to be guessed.

**Comment by razsteinmetz** [comment]
I know its not a bug, maybe (i think it does) a list of known situations like that (there was a similar issues with the word Us in the title that was taken as country code) that the package should scan. Also absolute episode over 100 is very unlikely.

**Comment by tsimmons** [comment]
Just following up, it seems also to miss other shows who's title is numeric, for example: 1923.S01E02.720p.HEVC.x265-MeGusta.mp4
```
GuessIt found: {
    "year": 1923,
    "season": 1,
    "episode": 2,
    "screen_size": "720p",
    "video_codec": "H.265",
    "video_profile": "High Efficiency Video Coding",
    "release_group": "MeGusta",
    "container": "mp4",
    "mimetype": "video/mp4",
    "type": "episode"
}
```

**Comment by Toilal** [comment]
Sorry, but there's no way to fix those issues guys. Use `expected_title`, and keep in mind that guessit is designed to work with any filename pattern.
