### ISSUE TITLE
Some tests are failing in guessit 3.4.3

### ISSUE THREAD

**Issue by jorti** [guessit-io/guessit#724]
I'm building guessit version 3.4.3 to package it in Fedora and some tests are failing. Please, see the tests log:

https://gist.github.com/jorti/4f4a98c35af98164a8c490d6eeef842f

**Comment by grawlinson** [comment]
I can confirm this is occurring on Arch Linux with the exact 5 failures.

**Comment by jorti** [comment]
Tests are still failing in 3.5.0

**Comment by Toilal** [comment]
It seems Arch Linux has issue with "mimetype": "video/x-matroska", i'll just remove those checks from failing tests
