### ISSUE TITLE
Not recognising absolute episode numbers in UFC Fight Night

### ISSUE THREAD

**Issue by heloid** [guessit-io/guessit#726]
For: UFC.Fight.Night.201.Walker.vs.Hill.Prelims.1080p.WEB-DL.H264.Fight-BB
GuessIt found: {
    "title": "UFC Fight Night",
    "season": 2,
    "episode": 1,
    "episode_title": "Walker vs Hill Prelims",
    "screen_size": "1080p",
    "source": "Web",
    "video_codec": "H.264",
    "release_group": "Fight-BB",
    "type": "episode"
}

Absolute episode number should be 201.

**Comment by Toilal** [comment]
default behavior is to guess 201 as season 2 episode 1. Use `--episode-prefer-number` option to get the result you want.

```
guessit -E UFC.Fight.Night.201.Walker.vs.Hill.Prelims.1080p.WEB-DL.H264.Fight-BB
For: UFC.Fight.Night.201.Walker.vs.Hill.Prelims.1080p.WEB-DL.H264.Fight-BB
GuessIt found: {
    "title": "UFC Fight Night",
    "episode": 201,
    "episode_title": "Walker vs Hill Prelims",
    "screen_size": "1080p",
    "source": "Web",
    "video_codec": "H.264",
    "release_group": "Fight-BB",
    "type": "episode"
}
```
