### ISSUE TITLE
Wrong Audio Codec and Release group

### ISSUE THREAD

**Issue by a-anand-91119** [guessit-io/guessit#728]
Consider a file `The.Movie.2016.2160p.UHD.BluRay.REMUX.HDR.HEVC.DTS-X-NOGROUP`

The extracted details are:
```
audio_codecL DTS
release_group: X-NOGROUP
```

Where the audio_codec and release groups are wrong.
Expected:
```
audio_codec: DTS-X
release_group: NOGROUP
```

**Comment by ratoaq2** [comment]
Fixed on master: 188ec28c0af83d0634ad450a9048f2799a131589
