### ISSUE TITLE
Bazarr told me to report a problem here

### ISSUE THREAD

**Issue by MrSaiclops** [guessit-io/guessit#729]
I wish I could give more details but I'm not skilled in the art of parsing code. Log can be found [here](https://docs.google.com/document/d/1xL2QFCOP5tm8OuY_WetUSTr0Zl-Fi1HuSZWEnwXuEio/edit?usp=sharing).

Thanks!

**Comment by Toilal** [comment]
Can't reproduce with last guessit version
