### ISSUE TITLE
pyMedusa: GuessitException('An internal error has occured in guessit

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [guessit-io/guessit#738]
[Guessit_Error.log](https://github.com/guessit-io/guessit/files/10422717/Guessit_Error.log)
[pyMedusa Logs.zip](https://github.com/guessit-io/guessit/files/10422721/pyMedusa.Logs.zip)

this is starting to become beyond frustrating with the amount of "GuessitException" errors I have been getting in the last 48 hours

<img width="2960" alt="Screen Shot 2023-01-16 at 4 16 32 pm" src="https://user-images.githubusercontent.com/2242880/212604603-548e355b-dc7e-408f-aac6-fe8ad73956c3.png">

**Comment by ratoaq2** [comment]
You should report this issue in Medusa repository. The issue happens in a Medusa's custom guessit rule
