### ISSUE TITLE
Request: Chat-GPT integration

### ISSUE THREAD

**Issue by snickers2k** [guessit-io/guessit#780]
wouldn't it make sense to simply ask chatgpt these days?

 works even for crypted filenames:
 (O is a 0)

> C0n.Man.2018.German.DL.1080p.BluRay.x264-LeetHD
> 
> Sure! Here is the breakdown of the filename along with the IMDb link for “Con Man” (2018):
> 
> 	1.	C0n.Man.2018: This is the title of the movie (Con Man) and the year of release (2018).
> 	2.	German: The movie is in German.
> 	3.	DL: Dual Language, meaning the movie is available in two languages (likely German and English).
> 	4.	1080p: The video resolution is 1080 pixels (Full HD).
> 	5.	BluRay: The source of the video is a BluRay disc.
> 	6.	x264: The video is encoded using the x264 codec.
> 	7.	LeetHD: This is the name of the release group that released this version.
> 
> In summary, this is a 1080p BluRay version of the movie “Con Man” from 2018, in German, encoded with x264, and released by the group LeetHD.
> 
> For more information about the movie, you can visit its [IMDb page](https://www.imdb.com/title/tt5689134/) ￼.

**Comment by Toilal** [comment]
Maybe, but I won't integrate ChatGPT inside guessit as it's designed to be a standalone tool.
